#! /bin/bash
##
## Copyright (c) 2024 Numurus, LLC <https://www.numurus.com>.
##
## This file is part of nepi-engine
## (see https://github.com/nepi-engine).
##
## License: 3-clause BSD, see https://opensource.org/licenses/BSD-3-Clause
##

# Stop NEPI RUI Process

sudo kill $(ps aux | grep 'run_webserver.py' | awk '{print $2}') >/dev/null 2>&1


