#! /bin/bash
##
## Copyright (c) 2024 Numurus, LLC <https://www.numurus.com>.
##
## This file is part of nepi-engine
## (see https://github.com/nepi-engine).
##
## License: 3-clause BSD, see https://opensource.org/licenses/BSD-3-Clause
##

# Start NEPI Engine Process
#echo "Fixing nepi_storage ownership"
#sudo chown -R nepi:nepi /mnt/nepi_storage/
sudo -v
echo "Fixing nepi_config folder ownership"
sudo chown -R nepi:nepi /mnt/nepi_config/
bash /opt/nepi/nepi_engine/etc/nepi_env/nepi_launch.sh
