#! /bin/bash
##
## Copyright (c) 2024 Numurus, LLC <https://www.numurus.com>.
##
## This file is part of nepi-engine
## (see https://github.com/nepi-engine).
##
## License: 3-clause BSD, see https://opensource.org/licenses/BSD-3-Clause
##

# Start NEPI License System
echo "Starting NEPI License Processes"
gnupg_folder=/home/nepi/.gnupg
if [[ ! -d $gnupg_folder ]]; then
    echo "GNUPG folder not found at ${gnupg_folder}"
else
    sudo chmod 0700 $gnupg_folder
    find "${gnupg_folder}" -type f -exec sudo chmod 600 {} +
    sudo chown -R root:root $gnupg_folder
    sudo python /opt/nepi/etc/license/nepi_check_license.py
fi

