#! /bin/bash
##
## Copyright (c) 2024 Numurus, LLC <https://www.numurus.com>.
##
## This file is part of nepi-engine
## (see https://github.com/nepi-engine).
##
## License: 3-clause BSD, see https://opensource.org/licenses/BSD-3-Clause
##

#source /opt/nepi/etc/load_system_config.sh

# Start NEPI Process Management services
suser=$(id -un)
echo "Starting supervisor as user ${suser}"
for i in {1..10}; do
  echo "$i"
  sudo service supervisor start
  echo "supervisor stopped running"
  sleep 1
done


