####################################################
# NEPI DOCKER SYSTEM CONFIG

# NEPI FILE SYSTEM A
# Conatiner Info Updated at Import-Time
NEPI_FSA: nepi_fs_a
NEPI_FSA_NAME: nepi
NEPI_FSA_TAG: unknown
NEPI_FSA_ID: unknown
NEPI_FSA_VERSION: 0
NEPI_FSA_SIZE_MB: 0
NEPI_FSA_HW_TYPE: unknown
NEPI_FSA_HW_MODEL: unknown
NEPI_FSA_BUILD_DATE: 0
NEPI_FSA_DESCRIPTION: unknown
# NEPI FILE SYSTEM B
# Conatiner Info Updated at Import-Time
NEPI_FSB: nepi_fs_b
NEPI_FSB_NAME: nepi
NEPI_FSB_TAG: unknown
NEPI_FSB_ID: unknown
NEPI_FSB_VERSION: 0
NEPI_FSB_SIZE_MB: 0
NEPI_FSB_HW_TYPE: unknown
NEPI_FSB_HW_MODEL: unknown
NEPI_FSB_BUILD_DATE: 0
NEPI_FSB_DESCRIPTION: unknown
# NEPI RUNNING FILE SYSTEM
# Running Container Info Populated at Run-Time
NEPI_RUNNING: 0
NEPI_RUNNING_FS: unknown
NEPI_RUNNING_TAG: unknown
NEPI_RUNNING_ID: unknown
NEPI_RUNNING_LAUNCH_TIME: 2025-09-12
# NEPI RESTART FILE SYSTEM
# NEPI Image Restarting Info
NEPI_RESTARTING: 0
# NEPI EXPORT FILE SYSTEM
# NEPI Image Export Info
NEPI_EXPORT_NAME: unknown
NEPI_EXPORT_TAG: unknown
NEPI_EXPORT_VERSION: 0
NEPI_EXPORT_SIZE_MB: 0
NEPI_EXPORT_HW_TYPE: unknown
NEPI_EXPORT_HW_MODEL: unknown
NEPI_EXPORT_BUILD_DATE: 0
NEPI_EXPORT_DESCRIPTION: unknown
NEPI_EXPORTING: 0
# NEPI IMPORT FILE SYSTEM
# NEPI Image to Import to Inactive File System
NEPI_IMPORT_FILE_PATH: /mnt/nepi_storage/nepi_images
NEPI_IMPORT_NAME: unknown
NEPI_IMPORT_TAG: unknown
NEPI_IMPORT_DATE: unknown
NEPI_IMPORTING: 0
# NEPI CONTAINER MANAGEMENT
# Run Settings Managed by NEPI Docker System
NEPI_ACTIVE_FS: nepi_fs_a
NEPI_INACTIVE_FS: nepi_fs_b
NEPI_FS_SWITCH: 0
NEPI_FS_RESTART: 0
NEPI_FS_IMPORT: 0
NEPI_FS_EXPORT: 0
NEPI_BOOT_TIME_SEC: 20
NEPI_MAX_FAIL_COUNT: 3
NEPI_FAIL_COUNT: 0
# NEPI MANAGED SERVICE TRIGGERS
NEPI_WIRED: 0
NEPI_WIFI: 0
NEPI_DHCP: 0
NEPI_NTP: 0
NEPI_RUNNING_FS_ID: 0
