NEPI_FSA: nepi_fs_a
NEPI_FSA_TAG: unknown
NEPI_FSA_ID: unknown
NEPI_FSA_NAME: unknown
NEPI_FSA_VERSION: unknown
NEPI_FSA_SIZE_MB: unknown
NEPI_FSA_HW_TYPE: unknown
NEPI_FSA_SW_DESC: unknown
NEPI_FSA_BUILD_DATE: unknown
NEPI_FSA_DESCRIPTION: unknown
NEPI_FSB: nepi_fs_b
NEPI_FSB_TAG: unknown
NEPI_FSB_ID: unknown
NEPI_FSB_NAME: unknown
NEPI_FSB_VERSION: unknown
NEPI_FSB_SIZE_MB: unknown
NEPI_FSB_HW_TYPE: unknown
NEPI_FSB_SW_DESC: unknown
NEPI_FSB_BUILD_DATE: unknown
NEPI_FSB_DESCRIPTION: unknown
NEPI_STARTING: 0
NEPI_RUNNING: 0
NEPI_RUNNING_FS: unknown
NEPI_RUNNING_TAG: unknown
NEPI_RUNNING_ID: unknown
NEPI_RUNNING_TIME: unknown
NEPI_EXPORT_FILE: unknown
NEPI_EXPORT_FS:  unknown
NEPI_EXPORT_TAG: unknown
NEPI_EXPORTING: 0
NEPI_IMPORT_FILE: unknown
NEPI_IMPORT_FS:  unknown
NEPI_IMPORT_TAG: unknown
NEPI_IMPORTING: 0
NEPI_ACTIVE_FS: nepi_fs_a
NEPI_INACTIVE_FS: nepi_fs_b
NEPI_FS_SWITCH: 0
NEPI_FS_RESTART: 0
NEPI_FS_IMPORT: 0
NEPI_FS_EXPORT: 0
NEPI_ETC_HOSTNAME_UPDATE: 0
NEPI_ETC_TIME_NTPS_UPDATE: 0
NEPI_ETC_WIRED_STATIC_UPDATE: 0
NEPI_ETC_WIRED_ALIASES_UPDATE: 0
NEPI_ETC_WIRED_DHCP_UPDATE: 0
NEPI_ETC_WIFI_ENABLE_UPDATE: 0
NEPI_ETC_WIFI_LOW_POWER_UPDATE: 0
NEPI_ETC_WIFI_CLIENT_UPDATE: 0
NEPI_ETC_WIFI_ACCESS_POINT_UPDATE: 0
NEPI_MAX_FAIL_COUNT: 1
NEPI_FAIL_COUNT: 0
NEPI_RETRY_COUNT: 10
NEPI_RESTARTING: 0
#If NEPI_AB_FS is enabled, the NEPI docker service will manage an Active NEPI container image,
#   and an Inactive Image used for backup and recovery purposes. If NEPI_AB_FS is enabled, 
#   you can switch between the current Active and Inactive A B containers
#   with the terminal command "nepiswitch".
# NOTE: If NEPI_AB_FS is enabled, and your Docker containe folder does not have the required
#   free hard drive space available, NEPI_AB_FS will be set back to disabled.
NEPI_AB_FS: 0
# IF NEPI_RM_PS is disabled, NEPI containers that start successfully will not be removed,
#   unless new images are commited or installed, or nepistop command is called.
NEPI_RM_PS: 1

