####################################################
### NEPI USER SETTINGS
####################################################
# NEPI USERS
NEPI_USER: nepi
NEPI_ADMIN_USER: nepiadmin
NEPI_HOST_USER: nepihost
# NEPI USER SETTINGS
NEPI_USER_PW: nepi
NEPI_ADMIN_PW: nepiadmin
NEPI_HOST_PW: nepi
# Set NEPI_ALLOWS_USERS to 1 to allow non-NEPI user accounts
# NOTE: if set to 0, all none-nepi user accounts will be removed
#  during etc update processing
NEPI_ALLOWS_USERS: 0

####################################################
# NEPI SYSTEM SETTINGS
####################################################
# Set the NEPI System Name
NEPI_DEVICE_ID: device1
# NEPI Model Description
NEPI_DEVICE_MD: uknown
# NEPI device's serial number (6 digits starting with non-zero)
NEPI_DEVICE_SN: '999999'
# NEPI Build Version Name
NEPI_VERSION: XpXpX
# NEPI Software Description
NEPI_SW_DESC: uknown


####################################################
### NEPI NETWORK SETTINGS
####################################################
## WIRED NETWORK SETTINGS
# Set the NEPI device's wired network interface name
NEPI_WIRED_INTERFACE: eth0
# Set the NEPI device's primary IP address
NEPI_IP: 192.168.179.103
# Set the NEPI device's primary IP Gatway address, or set to NONE
NEPI_IP_GATEWAY: NONE
# Add an IP address Alias on top of NEPI's Primary IP address (NEPI_IP), or set to NONE.
# NOTE: NEPI IP aliases are useful if you need to connect to other devices on the Network
#  like IP cameras configured with a different IP subnet then the NEPI_IP value. 
NEPI_ALIAS_IPS: NONE
# Add an IP address Alias on top of NEPI's Primary NTP address (time1.google.com), or set to NONE.
# NOTE: If the subnet of your desired NTP source IP address is different then NEPI_IP's subnet,
#   you will need to add an IP address with the NTP source's IP subnet to NEPI_ALIAS_IPS with that
#   subnet
NEPI_NTP_IPS: 192.168.179.5
# Enable Wired DHCP Wired Internet Connectivity on Startup. 
# NOTE: If enabled, the NEPI device will have internet connectiviy if connected to
#  a router with internet access. 
NEPI_WIRED_DHCP_ENABLED: 1
# Set the SSH Port that NEPI listens to, on top of the standard NEPI Host port (22).
NEPI_SSH_PORT: 2222
## WIFI NETWORK SETTINGS
# Set the NEPI device's WiFi hardware interface name
# NOTE: If set to "uknown", the first detected WiFi harware will be used
#  if set to NONE, wifi hardware and processes will be disabled
NEPI_WIFI_INTERFACE: uknown
# Enable WiFi Client Connectivity on Startup if WiFi Adapter Present. 
# NOTE: If enabled, the NEPI device will enable the device's WiFi hardware on startup,
#   and start WiFi client connection processes. If enabled and the setup proccess 
#   fails to enable harware, NEPI_WIFI_ENABLED value will be reset to 0 and
#   client/access_point settings/changes will be ignored.
NEPI_WIFI_ENABLED: 1
# Enable WiFi Low Power Mode if NEPI_WIFI_ENABLED=1. 
NEPI_WIFI_LOW_POWER_ENABLED: 1
# Enable WiFi Client Connectivity on Startup if NEPI_WIFI_ENABLED=1. 
NEPI_WIFI_CLIENT_ENABLED: 0
# Set Client Defualt Credentials or NONE
NEPI_WIFI_CLIENT_ID: NONE
NEPI_WIFI_CLIENT_PW: NONE
# Enable WiFi Access Point Connectivity on Startup if NEPI_WIFI_ENABLED=1. 
NEPI_WIFI_ACCESS_POINT_ENABLED: 0
# Set Access Point Defualt Credentials
NEPI_WIFI_ACCESS_POINT_ID: nepi_device_ap
NEPI_WIFI_ACCESS_POINT_PW: nepi_device_ap

# SET ROS MASTER IP Address. Will fall back to NEPI_IP if not found
NEPI_ROS_IP: 192.168.179.103
NEPI_ROS_PORT: 11311

####################################################
# NEPI SOFTWARE Config
####################################################
NEPI_PYTHON: X.X
NEPI_ROS: uknown
NEPI_HAS_CUDA: 0
NEPI_CUDA_VERSION: X.X
NEPI_HAS_XPU: 0

####################################################
### NEPI HARDWARE SETTINGS
####################################################
# NEPI Hardware Host Options: jetson, arm64, amd64.
NEPI_HW_TYPE: uknown
# NEPI Hardware Host Model Options: ORIN, XAVIER, TX2, NANO, RPI4, GENERIC.
NEPI_HW_MODEL: uknown

####################################################
# NEPI CONTAINER SETTINGS
####################################################
# Set whether NEPI is running in a docker container
NEPI_IN_CONTAINER: 1
NEPI_GB_CONTAINER: 20
# If NEPI_IN_CONTAINER=1, set whether NEPI supports a recovery mode
# Note: If NEPI_RECOVERY_ENABLED enabled and NEPI_IP is not 192.168.179.103,
#   the NEPI Host system will run with 
#   NEPI factory config ip address 192.168.179.103 before switching to
#   NEPI system config configured ip address for 10 seconds
NEPI_RECOVERY_ENABLED: 1
# If NEPI_IN_CONTAINER=1, set the time in seconds to wait for 
#   NEPI software to start and set success flags.
# NOTE: This is the time NEPI Docker service will
#   wait for a NEPI container to start successfully
#   before retrying with backup and fallback configurations.
# NOTE:  This time may vary on different hardware configurations,
#   so best to start with a longer wait and adjust aftertwards to
#   a lower value if needed.
NEPI_BOOT_TIME: 30

####################################################
# NEPI MANAGED SERVICES 
####################################################
# Set NEPI_MANAGES_XXX service values beow to 0 or 1 to turn off or on NEPI management of that service
# Note, if disabled:
#    that system service configuration must be done manually.
#   -DOCKER-If enabled, the Hoset OS's docker config will be update to use the NEPI_DOCKER path set below.
#   -HOSTNAME-Configure the HOST OS etc/hostname file with desired network hostname -> NEPI_DEVICE_ID.
#   -HOSTNAME-Configure the HOST OS etc/hosts file with nepi ip alias -> NEPI_DEVICE_ID.
#   -NETWORK-Ensure on the Host OS that the NEPI_IP address enabled as a static ip address -> NEPI_IP nepi.
#   -NETWORK-Setup and Enable DHCP Client for internet connections if needed.
#   -TIME-Setup and configure Chrony time management service.
#   -TIME-Configure Chrony's NTP service to listen for -> NEPI_NTP_IP address.
#   -SSH-Configure Host OS ssh setup for on port 22 with desired login credetials and keys. NEPI will still be availbe on ssh port 2222.
#   -SOFTWARE-NEPI will not start any NEPI software management processes on startup
NEPI_MANAGES_HOSTNAME: 0
NEPI_MANAGES_NETWORK: 0
NEPI_MANAGES_TIME: 0
NEPI_MANAGES_SSH: 0
NEPI_MANAGES_SHARE: 0
NEPI_MANAGES_SOFTWARE: 0
# If NEPI_IN_CONTAINER=1, set whether NEPI managine docker software system
# Note: If enabled, NEPI will setup docker configuration,
#   and use /mnt/nepi_docker as the folder docker images are stored
NEPI_MANAGES_DOCKER: 0

####################################################
### NEPI PARTITION SETTINGS
####################################################

# Set to partition path if running directly on device's file system
# Or "CONTAINER" if running in a docker container
NEPI_BOOT_DEVICE: CONTAINER
NEPI_FS_DEVICE: CONTAINER
NEPI_STORAGE_DEVICE: CONTAINER

####################################################
### NEPI REQUIRED FOLDERS
####################################################
# NEPI_DOCKER folder is where Docker Images will be stored if NEPI_MANAGES_DOCKER=1
NEPI_DOCKER: /mnt/nepi_docker
# NEPI_CONFIG folder is where NEPI stores it's configuration files
NEPI_CONFIG: /mnt/nepi_config
# NEPI_STORAGE folder is where NEPI user data and files are stored
NEPI_STORAGE: /mnt/nepi_storage

####################################################
# NEPI FOLDERS CONFIG
####################################################
# NEPI Folders
NEPI_SOURCE: /home/nepidev
NEPI_ENV: nepi_env
NEPI_HOME: /home/nepi
NEPI_BASE: /opt/nepi
NEPI_RUI: /opt/nepi/nepi_rui
NEPI_ENGINE: /opt/nepi/nepi_engine
NEPI_ETC: /opt/nepi/etc
NEPI_SCRIPTS: /opt/nepi/scripts
# NEPI Config Paths
NEPI_DOCKER_CONFIG: /mnt/nepi_config/docker_cfg
NEPI_FACTORY_CONFIG: /mnt/nepi_config/factory_cfg
NEPI_SYSTEM_CONFIG: /mnt/nepi_config/system_cfg
NEPI_USR_CONFIG: /mnt/nepi_storage/user_cfg

####################################################
# NEPI IMAGE IMPORT EXPORT CONFIG
####################################################
# Set to paths where NEPI will use for importing and exporting
#  NEPI tar container images.
# NOTE: It is recommended that these folders be create as their own partitions
#   so that these files are not affected by any device file system changes
NEPI_IMPORT_PATH: /mnt/nepi_storage/nepi_images
NEPI_EXPORT_PATH: /mnt/nepi_storage/nepi_images
