#!/bin/bash

##
## Copyright (c) 2024 Numurus <https://www.numurus.com>.
##
## This file is part of nepi setup tools (nepi_setup) repo
## (see https://github.com/nepi-engine/nepi_setup)
##
## License: nepi setup tools are licensed under the "Numurus Software License", 
## which can be found at: <https://numurus.com/wp-content/uploads/Numurus-Software-License-Terms.pdf>
##
## Redistributions in source code must retain this top-level comment block.
## Plagiarizing this software to sidestep the license obligations is illegal.
##
## Contact Information:
## ====================
## - mailto:nepi@numurus.com
##


# This file contains nepi bash utility functions

#echo "########################"
#echo "STARTING NEPI Bash Utils"
#echo "########################"




if [[ ! -n $CONFIG_USER ]]; then
    CONFIG_USER=$(id -un)
    if [[ ${CONFIG_USER} == 'root' ]]; then
        CONFIG_USER=$SUDO_USER
    fi
fi
if [[ ! -n $CONFIG_USER ]]; then
    id -nu 1000
fi

export CONFIG_USER=$CONFIG_USER
export USER=$CONFIG_USER


CURRENT_DIR=$(pwd)
nepi_alias_file=$(basename "${BASH_SOURCE[1]}")
export BASH_FOLDER=$(cd -P "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)
#echo "BASH_FOLDER ${BASH_FOLDER}"

##############################
##### NEPI SETTINGS #####
export NEPI_BASH_UTILS=${BASH_FOLDER}/.nepi_bash_utils

export NEPI_MODE=SYSTEM

export NEPI_USER=nepi
export NEPI_ADMIN_USER=nepiadmin
export NEPI_HOST_USER=nepihost

export NEPI_IP=192.168.179.103
export NEPI_DEVICE_ID=device1
export NEPI_RECOVERY_DEVICE_ID=device1
export NEPI_RECOVERY_IP=192.168.179.103
export NEPI_IN_CONTAINER=1
export REMOTE_IP=192.168.179.5


export NEPI_HOME=/home/$CONFIG_USER
export NEPI_BASE='/opt/nepi'
export NEPI_ENGINE=${NEPI_BASE}/nepi_engine
export NEPI_STORAGE='/mnt/nepi_storage'
export NEPI_FACTORY_CONFIG='/mnt/nepi_config/factory_cfg'
export NEPI_SYSTEM_CONFIG='/mnt/nepi_config/system_cfg'
export NEPI_DOCKER_CONFIG='/mnt/nepi_config/docker_cfg'

export NEPI_SSH_FOLDER="/home/${CONFIG_USER}/.ssh"
export NEPI_SSH_KEY_FILE=nepi_default_ssh_key
export NEPI_SSH_KEY_PATH="${NEPI_SSH_FOLDER}/${NEPI_SSH_KEY_FILE}"

export NEPI_TARGET_IP=$NEPI_IP
export NEPI_TARGET_USERNAME=$NEPI_USER
export NEPI_TARGET_SRC_DIR=${NEPI_STORAGE}/nepi_src

export NEPI_REPO_ADDRESS_DEFAULT='git@github.com:nepi-engine/nepi_engine_ws.git'
export NEPI_REPO_ADDRESS='git@github.com:nepi-engine/nepi_engine_ws.git'
export NEPI_REPO_NAME=$(basename "${NEPI_REPO_ADDRESS%.*}")
export NEPI_REPO_FOLDER="/home/${CONFIG_USER}/${NEPI_REPO_NAME}"

export NEPI_BUILD_REPO_NAME=${NEPI_REPO_NAME}
export NEPI_BUILD_REPO_FOLDER="${NEPI_STORAGE}/nepi_src/${NEPI_BUILD_REPO_NAME}"

export NEPI_SETUP_REPO_NAME='nepi_setup'
export NEPI_SETUP_REPO_FOLDER="/home/${CONFIG_USER}/${NEPI_SETUP_REPO_NAME}"


alias nepimode="
echo ${NEPI_MODE}
"

function NSETUP() {
  if [[ -d $NEPI_REPO_FOLDER ]]; then
    NEPI_SETUP_FOLDER="${NEPI_REPO_FOLDER}/nepi_setup"
    # if [[ -d ${NEPI_SETUP_REPO_FOLDER} ]]; then
    #   rm -r $NEPI_SETUP_REPO_FOLDER >/dev/null 2>&1
    # fi
  elif [[ -d $NEPI_BUILD_REPO_FOLDER ]]; then
    NEPI_SETUP_FOLDER="${NEPI_BUILD_REPO_FOLDER}/nepi_setup"
    # if [[ -d ${NEPI_SETUP_REPO_FOLDER} ]]; then
    #   rm -r $NEPI_SETUP_REPO_FOLDER >/dev/null 2>&1
    # fi
  else
    NEPI_SETUP_FOLDER="${NEPI_SETUP_REPO_FOLDER}"
  fi
  echo "${NEPI_SETUP_FOLDER}"
}
export -f NSETUP

function NRUI_IP() {
  rui_ip=$NEPI_IP
  if [[ ${NEPI_MODE} == 'HOST' ]]; then
    rui_ip=localhost
  fi
  echo "${rui_ip}"
}
export -f NRUI_IP




###############################

utilsn=""

###################################
# System Check Functions
###################################

# Function to check if a variable is not blank
function is_not_blank() {
  # Strip all whitespace characters using parameter expansion (Bash specific)
  val=$1
  if [[ -n $val ]]; then
    local trimmed_var="${val//[[:space:]]/}"
    
    # Check if the length of the trimmed string is non-zero
    if [[ -n "$trimmed_var" ]]; then
      return 0
    else
      return 1
    fi
  else
    return 1
  fi
}

export -f is_not_blank

function is_valid_uid() {
    local input=$1

    # Regular expression for a common Linux username format
    # Starts with a lowercase letter or underscore, followed by 0-31 lowercase letters, numbers, hyphens, or underscores.
    USERNAME_REGEX="^[a-z_][a-z0-9_-]{0,31}$"

    if [[ ! "$input" =~ $USERNAME_REGEX ]]; then
        echo "Variable '$input' is NOT a valid Linux username format."
    fi
    return 0
    }
export -f is_valid_uid

function is_valid_pw() {
    local input=$1

    if [ -z "$input" ]; then
        echo "Passwords can not be blank string."
        return 1
    fi

    if [[ "$input" == "encrypted" ]]; then
        echo "Password already encrypted"
        return 1
    fi

  case "$input" in
      *[[:space:]]*|*/*|*\\*)
          echo "Passwords can not contain spaces or slashes."
          ;;
      *)
  esac
    return 0
    }
export -f is_valid_pw


function is_valid_did() {
    local input=$1

    # Check for empty string
    if [ -z "$input" ]; then
        echo "NEPI Device ID's can not be blank string."
        return 1
    fi
    # Check that first char is a letter
    if [[ ! "$input" =~ ^[a-zA-Z] ]]; then
        echo "The first character or NEPI Device ID must be a letter."
        return 1
    fi
    # Check if input is only letters numbers and underscores with no spaces
    if [[ ! "$input" =~ ^[a-zA-Z0-9_]+$ ]]; then
        echo "NEPI Device ID's must be only letters, numbers, and underscores with no spaces."
        return 1
    fi
    return 0
    }
export -f is_valid_did

function is_valid_string() {
    local input=$1

    # Check for empty string
    if [ -z "$input" ]; then
        echo "NEPI Model Name can not be blank string."
        return 1
    fi
    return 0
    }
export -f is_valid_string

function is_valid_sn() {
    local input=$1
    # Check for empty string
    if [ -z "$input" ]; then
        echo "NEPI Serial Numbers can not be blank string."
        return 1
    fi
    # Check if serial number is valid 6 digit number
    if [[ ! "$input" =~ ^[0-9]{6}$ ]]; then
        echo "'$input' is NOT a 6-digit number."
        return 1
    fi

    if [[ ! "$input" =~ ^[1-9][0-9]* ]]; then
        echo "'NEPI Serial Numbers must start with non-zero number."
        return 1
    fi

    return 0
    }
export -f is_valid_sn

function is_valid_ipv4() {
    local input=$1

    # Check if the format matches a general IP pattern (e.g., 1.2.3.4)
    if ! [[ $input =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        echo "Not a valid IP Address format #.#.#.#"
        return 1 # Invalid format
    fi

    # Split the IP address into octets and check their values
    IFS='.' read -r -a octets <<< "$input"
    for octet in "${octets[@]}"; do
        if (( octet < 0 || octet > 255 )); then
            return 1 # Octet out of range
        fi
    done


    return 0 # Valid IP address
}
export -f is_valid_ipv4
  

function is_valid_netmask() {
    local input=$1
    if [[ -n "$input" ]]; then
      if [[ "$input" -ge 0 && "$input" -le 32 ]]; then
        return 0 # Valid Netmask address
      else
        echo "Not a valid Netmask between 0 and 32"
        return 1 # Invalid format
      fi
    else
        echo "Netmask empty, not valid"
        return 1 # Invalid format
    fi
}
export -f is_valid_netmask



function is_valid_ipv4_netmask() {
    local input=$1
    ip="${input%%/*}"
    nm=''
    if [[ "$input" == *"/"* ]]; then
      nm="${input#*/}"
    fi
    if is_valid_ipv4 $ip; then
      if is_valid_netmask $nm; then
        return 0 # Valid IP and Netmask
      else
        return 1 # Invalid Netmask
      fi
    else
      return 1 # Invalid IP address format
    fi
}
export -f is_valid_ipv4_netmask


function is_valid_path() {
    local input=$1
    if [[ ! -e "$input" ]]; then
        echo "'Path ${input} not found."
        return 1
    fi
    return 0 # Valid folder
}
export -f is_valid_path

function is_valid_folder() {
    local input=$1
    if [[ ! -d "$input" ]]; then
        echo "'Path ${input} not found."
        return 1
    fi
    return 0 # Valid folder
}
export -f is_valid_folder

function is_valid_file() {
    local input=$1
    if [[ ! -f "$input" ]]; then
        echo "'Path ${input} not found."
        return 1
    fi
    return 0 # Valid folder
}
export -f is_valid_file

function is_valid_bool() {
    local input=$1
    if [[ "$input" != "1" && "$input" != "0" ]]; then
        echo "'Input not valid. Enter a 1 or 0"
        return 1
    fi
    return 0 # Valid Bool
}
export -f is_valid_bool



function is_valid_internet(){
    if ! ping -c 2 google.com; then
        echo "No Internet Connection"
        return 1
    else
        echo "Internet Connected"
        return 0
    fi
}
export -f is_valid_internet


function is_valid_arm64(){
    arch_check="arm64"
    arch_val=$(uname -m)
    if [[ "$arch_val" == "aarch64" ]]; then
        echo "System Arch is ${arch_check}"
        return 0
    else
        return 1
    fi
}
export -f is_valid_arm64


function is_valid_jetson(){
if [ -f /etc/nv_tegra_release ]; then
        return 0
    else
        return 1
    fi
}
export -f is_valid_jetson

function is_valid_amd64(){
    arch_check="amd64"
    arch_val=$(uname -m)
    if [[ "$arch_val" == "x86_64" ]]; then
        echo "System Arch is ${arch_check}"
        return 0
    else
        return 1
    fi
}
export -f is_valid_amd64


function is_valid_cuda(){
    no_cuda=1
    lspci 2>/dev/null | grep -i nvidia
    if [[ "$?" -eq 0 ]]; then
      no_cuda=0
    else
      lspci 2>/dev/null | grep -i NVIDA
      if [[ "$?" -eq 0 ]]; then
        no_cuda=0
      fi  
    fi
    return $no_cuda
}
export -f is_valid_cuda


function is_valid_rpi(){
  if grep -q "Raspberry Pi" /proc/device-tree/model 2>/dev/null; then
    return 0
  else
    return 1
  fi
}
export -f is_valid_rpi


function is_space_avail_mb(){
    local check_path=$1
    local req_space=$2
    if ! is_valid_folder $check_path; then
      #echo "Not a valid folder ${check_path}"
      return 1
    else
      avail_space=$(path_space_mb $check_path)
      #echo "Aval Space: ${avail_space}"
      #echo "Req Space: ${req_space}"
      if [[ "$avail_space" -lt "$req_space" ]]; then
        #echo "Not enough space ${check_path}"
        return 1
      else
        return 0
      fi
    fi
}
export -f is_space_avail_mb

function is_space_avail_gb(){
    local check_path=$1
    local req_space=$2
    if ! is_valid_folder $check_path; then
      #echo "Not a valid folder ${check_path}"
      return 1
    else
      avail_space=$(path_space_gb $check_path)
      #echo "Aval Space: ${avail_space}"
      #echo "Req Space: ${req_space}"
      if [[ "$avail_space" -lt "$req_space" ]]; then
        #echo "Not enough space ${check_path}"
        return 1
      else
        return 0
      fi
    fi
}
export -f is_space_avail_gb

function is_nepi_path(){
    local check_path=$1
    if [[ ! -e "$check_path" ]]; then
      echo "Path not found at ${check_path}"
      return 1
    fi

    if [[ ":$check_path:" == *"${NEPI_BASE}"* ]]; then
      return 0
    fi

    if [[ ":$check_path:" == *"/mnt/nepi_storage"* ]]; then
      return 0
    fi

    if [[ ":$check_path:" == *"/mnt/nepi_config"* ]]; then
      return 0
    fi
    if [[ ":$check_path:" == *"/mnt/nepi_config"* ]]; then
      return 0
    fi
    if [[ ":$check_path:" == *"/home"* ]]; then
      return 0
    fi

    return 2
    
}
export -f is_nepi_path

function is_valid_email() {
    local email=$1
    # A simple regex for email validation (approximates RFC 5322)
    local regex="^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}$"

    if [[ "$email" =~ $regex ]]; then
        return 0  # Valid
    else
        return 1  # Invalid
    fi
}

export -f is_valid_email


utilsn="${utilsn}
################################
### SYSTEM CHECK FUNCTIONS
################################
*** These checks return 0 error value if true ***
is_not_blank = Check if variable is blank
is_valid_uid = Check for valid user id name
is_valid_pw = Check for valid use password
is_valid_did = Check for valid device id name
is_valid_string = Check that string is not empty
is_valid_sn = Check for valid nepi serial number
is_valid_ipv4 = Check for valid ip address
is_valid_netmask = Check for valid ip netmask
is_valid_ipv4_netmask = Check for valid ip and netmask
is_valid_path = Check for path
is_valid_folder = Check for folder
is_valid_file = Check for file
is_valid_bool = Check for valid bash bool - 0 or 1
is_valid_internet = Check for internet connection
is_valid_jetson = Check if device is an NVIDIA Jetson system
is_valid_arm64 = Check if device is arm64 arch
is_valid_amd64 = Check if device is amd64 arch
is_valid_cuda = Check if system has CUDA
is_valid_rpi = Check if system is on a Raspberry Pi
is_space_avail_mb = Check folder for REQ_SPACE in MB
is_space_avail_gb = Check folder for REQ_SPACE in GB
is_nepi_path = Check if path in either a nepi managed folder
is_valid_email = Check if email is valid format"



###################################
# System Util Functions
###################################

# echo variable value
function echovar(){
    local var_name="$1"
    echo "$var_name: ${!var_name}"
}
export -f echovar


function netlist() {
    # Use 'ip -4 -o addr show' for a consistent, machine-readable output for IPv4 addresses only
    # 'awk' is then used to parse the output and format it
    nlist=$(ip -4 -o addr show | awk '{
        # $netlist2 is the interface name, $4 is the IP address in CIDR format
        split($4, a, "/"); # Split the IP/CIDR to get just the IP address
        printf "%-9s  %s |\n", $2, a[1] ;
    }')
    if is_not_blank $nlist; then
        #echo "netlist = ${nlist}"
        counter=0
        new_n=1
        for word in $nlist; do
          #echo "got ${word}"
          if [[ $counter -eq 0 ]]; then
            aname=$(nmcli -g GENERAL.CONNECTION device show ${word})
            if [[ $? -eq 0 && -n $aname ]]; then
              printf "%s " "$aname"
            else
              printf "%s " "$word"
            fi
          elif [[ $counter -eq 1 ]]; then
              printf "%s " "| ${word}"
          fi
          if [[ $new_n -eq 1 ]]; then
            last_n=$word
            new_n=0
          fi
          ((counter++))
          if [[ $((counter % 3)) == 0 ]]; then
            counter=0
            new_n=1
            skip=0
            printf "\\n"
          fi
        done
        # Add a final newline if the total count isn't a multiple of 3,
        # ensuring the last line is processed.
        if [[ $((counter % 3)) != 0 ]]; then
          printf "\\n"
        fi
    else
      echo ''
    fi

}
export -f netlist



function netliststatic() {
    # Use 'ip -4 -o addr show' for a consistent, machine-readable output for IPv4 addresses only
    # 'awk' is then used to parse the output and format it
    nlist=$(ip -4 -o addr show | awk '{
        # $netlist2 is the interface name, $4 is the IP address in CIDR format
        split($4, a, "/"); # Split the IP/CIDR to get just the IP address
        printf "%-9s  %s |\n", $2, a[1] ;
    }')
    if is_not_blank $nlist; then
      #echo "netlist = ${nlist}"
      counter=0
      new_n=1
      last_n='lo'
      skip=0
      for word in $nlist; do
        #echo "got ${word}"
        if [[ ${word} == ${last_n} || "$word" == *"l4tbr"* || "$word" == *"rndis"* || "$word" == *"wlan"* || "$word" == *"docker"* ]]; then
          #echo "skipping ${word}"
          skip=1
        fi
        if [[ $skip -eq 0 ]]; then
          if [[ $counter -eq 0 ]]; then
            aname=$(nmcli -g GENERAL.CONNECTION device show ${word})
            if [[ $? -eq 0 && -n $aname ]]; then
              printf "%s " "$aname"
            else
              skip=1
            fi
          elif [[ $counter -eq 1 ]]; then
              printf "%s " "| ${word}"
          fi
        fi
        if [[ $new_n -eq 1 ]]; then
          last_n=$word
          new_n=0
        fi
        ((counter++))
        if [[ $((counter % 3)) == 0 ]]; then
          counter=0
          new_n=1
          skip=0
          printf "\\n"
        fi
      done
      # Add a final newline if the total count isn't a multiple of 3,
      # ensuring the last line is processed.
      if [[ $((counter % 3)) != 0 ]]; then
        printf "\\n"
      fi
    else
      echo ''
    fi


}
export -f netliststatic

function netsetstatic() {
    new_ip_netmask="$1"

    if ! systemctl is-active --quiet NetworkManager; then
      echo "NetworkManager not running"
      return 1
    fi

    if [[ -n $new_ip ]]; then
      if [[ ${new_ip_netmask} != 'auto' ]]; then
        new_ip_netmask=$(fix_ipv4_netmask $new_ip_netmask)
        if ! is_valid_ipv4_netmask $new_ip_netmask; then
          echo "Invalid Address/Netmask Combination ${net_ip}"
          return 1
        fi
      fi
    fi

    selected_adapter=''

    # Use 'ip -4 -o addr show' for a consistent, machine-readable output for IPv4 addresses only
    # 'awk' is then used to parse the output and format it
    nslist=$(netliststatic) 
    
    if ! is_not_blank $nslist; then
        echo "No Network Adapters Found"
        return 1
    fi
    echo $nslist
    # Set IFS to | and read into an array
    readarray -t adapters <<< "$nslist"
    adapters=("${adapters[@]:1}")
 
    # Check if there are any files
    if [[ ${#adapters[@]} -eq 0 ]]; then
        echo "No Network Adapters Found"
        return 1
    fi

    # Check if there are any adapters
    if [[ ${#adapters[@]} -eq 1 ]]; then
        line=${adapters[0]}
        delimiter=" |"
        selected_adapter=${adapter%%$delimiter*}
    fi

    if [[ -z $selected_adapter ]]; then
      echo ""
      echo "Select a Network Adapter to Update"
      echo "--------------------"
      echo ""
      select adapter in "${adapters[@]}"; do
          if [[ -n "$adapter" ]]; then
              delimiter=" |"
              selected_adapter=${adapter%%$delimiter*}
              break
          else
              echo "Invalid selection. Please try again."
          fi
      done
    fi
      
    if [[ ! -n $new_ip_netmask ]]; then
        echo ''

    fi
    
    # Output the full path of the selected file
    if [[ -n "$selected_adapter" ]]; then
        echo "Updating Network Adapter ${selected_adapter} with IP Address ${new_ip_netmask}"
        if systemctl is-active --quiet NetworkManager; then
          if [[ ${new_ip_netmask} == 'auto' ]]; then
            cmd='sudo nmcli con mod "'${selected_adapter}'" ipv4.method auto '
            echo $cmd
            eval "$cmd"     

            cmd='sudo nmcli con mod "'${selected_adapter}'" connection.autoconnect yes '
            echo $cmd
            eval "$cmd" 

            cmd='sudo nmcli connection up "'${selected_adapter}'"'
            #echo $cmd
            eval "$cmd"     
            echo ""
          else
            cmd='sudo nmcli connection modify "'${selected_adapter}'" \
                ipv4.addresses '${new_ip_netmask}' \
                ipv4.dns 8.8.8.8,8.8.4.4 \
                ipv4.method manual '
            echo $cmd
            eval "$cmd"     

            cmd='sudo nmcli connection up "'${selected_adapter}'"'
            #echo $cmd
            eval "$cmd"     
            echo ""
          fi
        fi

        return 0
        
    fi   
}

export -f netsetstatic

function netsetauto() {
  netsetstatic 'auto'
  return $?
}

export -f netsetauto

function netsetcustom() {
  netsetstatic $1
  return $?
}

export -f netsetcustom

function netsetnepi() {
  if [[ $NEPI_MODE == 'REMOTE' ]]; then
    ip="${REMOTE_IP%%/*}"
  else
    ip="${NEPI_IP%%/*}"
  fi
  netsetstatic $ip
  return $?
}

export -f netsetnepi

# ping internet
function pingi(){
    if ! ping -c 1 -W 1 google.com > /dev/null 2>&1; then
        echo "No Internet Connection"
        return 1
    else
        echo "Internet Connected"
    fi
}
export -f pingi

# ping self
function pings(){
    if [[ $NEPI_MODE == 'REMOTE' ]]; then
      ip="${REMOTE_IP%%/*}"
    else
      ip="${NEPI_IP%%/*}"
    fi
    if ! ping -c 1 -W 1 ${ip} > /dev/null 2>&1; then
        echo "No Connection at ${ip}"
        return 1
    else
        echo "Connected at ${ip}"
    fi
}
export -f pings



# ping nepi
function pingn(){
    ip="${NEPI_IP%%/*}"
    if ! ping -c 1 -W 1 ${ip} > /dev/null 2>&1; then
        echo "No NEPI Connection at ${ip}"
        return 1
    else
        echo "NEPI Connected at ${ip}"
    fi
}
export -f pingn


# ping nepi continously
function pingnc(){
  ping "${NEPI_IP%%/*}"
}
export -f pingnc


alias sbrc="
source /home/${CONFIG_USER}/.bashrc"


## NEPI deploy complete
function ubrc_remote() {
sudo -v
source $(NSETUP)/scripts/remote_bash_setup.sh $skip_software
source /home/${CONFIG_USER}/.bashrc
}

function ubrc_host() {
sudo -v
source $(NSETUP)/scripts/docker_bash_setup.sh $skip_software
source /home/${CONFIG_USER}/.bashrc
}

function ubrc_system() {
sudo -v
source $(NSETUP)/scripts/nepi_bash_setup.sh $skip_software
source /home/${CONFIG_USER}/.bashrc
}


function ubrc() {
sudo -v
nepi_mode=${NEPI_MODE}
echo "NEPI_MODE: ${nepi_mode}"
if [[ ${nepi_mode} == 'REMOTE' ]]; then 
  ubrc_remote
elif [[ ${nepi_mode} == 'HOST' ]]; then 
  ubrc_host
elif [[ ${nepi_mode} == 'SYSTEM' ]]; then 
  ubrc_system
fi
}


function ask_yes_no {
    read -p "$1 ([y]es or [N]o): " choice
    case "$(echo "$choice" | tr '[:upper:]' '[:lower:]')" in
        y|yes) echo "yes" ;;
        *) echo "no" ;;
    esac
}
export -f ask_yes_no



function nipa(){
  sudo -v
  file=/etc/network/interfaces.d/nepi_static_ip
  if [ ! -f "$file" ]; then
      return 2
  else
    addr=$(grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' "$file" | head -n 1)
    if [[ -n "$addr" ]]; then
      echo $addr
    else
      return 1
    fi
  fi 

}
export -f nipa


function naipa(){
  sudo -v
  file=/etc/network/interfaces.d/nepi_user_ip_aliases
  if [ ! -f "$file" ]; then
      return 2
  else
    addrs=$(grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' "$file")
    if [[ -n "$addrs" ]]; then
      echo $addrs
    else
      return 1
    fi
  fi 

}
export -f naipa

function nnipa(){
  sudo -v
  file=/etc/chrony/chrony.conf
  if [ ! -f "$file" ]; then
      return 1
  else
    addrs=$(grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' "$file")
    if [[ -n "$addrs" ]]; then
      echo $addrs
    else
      return 1
    fi
  fi 

}
export -f nnipa

function nnet(){
    sudo -v
    nepi_ip=$(nipa)
    if [[ -z "$nepi_ip" ]]; then
      return 1
    else
      ping -c 1 -W 1 $nepi_ip > /dev/null 2>&1
      if [ $? -ne 0 ]; then
        echo "Can't ping NEPI IP address: ${nepi_ip}"

        echo "Restarting Network"
        sudo systemctl restart networking
        wait
        ping -c 1 -W 1 $nepi_ip > /dev/null 2>&1
        if [ $? -ne 0 ]; then
          echo "Failed to connect NEPI IP address: ${nepi_ip}"
        fi
      fi
    fi
}
export -f nnet

function ndhcp(){
  sudo -v
  if nnet; then
    # This file sets up nepi bash aliases and util functions
    # Check for internet connection by pinging a reliable public DNS server (e.g., Google's 8.8.8.8)
    # -c 1: Send only one ping packet
    # -W 1: Wait for 1 second for a response
    ping -c 1 -W 1 8.8.8.8 > /dev/null 2>&1

    # Check the exit status of the ping command
    # 0 indicates success (internet connection)
    # Non-zero indicates failure (no internet connection)
    if [ $? -ne 0 ]; then
      echo "No internet connection detected. Will try and connect"

      echo "Enabling DHCP internet connection"
      echo "Killing existing DHCP clients"
      sudo kill $(ps aux | grep 'dhclient' | awk '{print $2}') >/dev/null 2>&1
      echo "Renewing dhclient"
      sudo dhclient -nw
      sleep 2
      nnet # Restart network
      wait
      if ! pingi; then
        return 1
      fi
    fi
    sudo kill $(ps aux | grep 'dhclient' | awk '{print $2}') >/dev/null 2>&1
  fi
}
export -f ndhcp


function nclock(){
      sudo -v
      # This file sets up nepi bash aliases and util functions
      # Check for internet connection by pinging a reliable public DNS server (e.g., Google's 8.8.8.8)
      # -c 1: Send only one ping packet
      # -W 1: Wait for 1 second for a response
      ping -c 1 -W 1 $(nnipa) > /dev/null 2>&1
      if [ $? -ne 0 ]; then
        ping -c 1 -W 1 8.8.8.8 > /dev/null 2>&1
        if [ $? -ne 0 ]; then
            echo "No Internet or NTP Server connection detected. Can't sync clocks"
            return 1 # Exit with a non-zero status to indicate an error
        fi
      fi

      
     
      if [[ "$(date +%Y)" -lt 2025 ]]; then
        echo "NTP Server connection detected. Will try to sync clocks"
        echo "Restarting chrony time service"
        sudo systemctl restart chronyd
        sleep 1
        sudo chronyc -a makestep > /dev/null 2>&1
      fi
      #chronyc waitsync 1
      # sudo chronyc -a makestep > /dev/null 2>&1
      # echo "Forcing clock sync"
      #sudo chronyc -a makestep > /dev/null 2>&1


    if [[ "$(date +%Y)" -lt 2025 ]]; then
        echo "Clock Not Updated"
        return 1
    else
        echo "Clock Updated"
    fi
}
export -f nclock


function ninet(){
  sudo -v
  echo "Running NEPI Internet Update Processes"
  ndhcp # Enable DHCP internet connection if needed
  wait
  sleep 1
  if ! nclock; then # Connect to NTP server
      return 1
  fi
}
export function ninet

function check_password() {
    local username=$1
    local pcheck=$2
    echo "$pcheck" | su -c true "$username" >/dev/null 2>&1
    local error=$?
    if [[ $error -eq 0 ]]; then
        return 0
    else
        ret=$(echo "$pcheck" | su -c true "$username" 2>/dev/null)
        if [[ ${ret} == 'This account is currently not available.' ]]; then
            return 0
        else
            return 1
        fi
    fi
}

export check_password


function change_password() {
        username=$1
        password=$2

        if [[ ${password} == "encrypted" ]]; then
            echo "Password for ${username} encrypted" 
            return 1
        fi
        if check_password ${username} ${password} ; then
            echo "Password unchanged" 
            return 1
        fi        

        if is_valid_pw $password; then

            OLD_HASH=$(sudo grep "^${username}:" /etc/shadow | cut -d: -f2)

            echo "${username}:${password}" | sudo chpasswd

            # After chpasswd
            NEW_HASH=$(sudo grep "^${username}:" /etc/shadow | cut -d: -f2)

            if [ "$OLD_HASH" != "$NEW_HASH" ]; then
                echo "Updated password for user ${username}"
                return 0
            else
                return 1
            fi
        else
            echo "Password update for user ${username} failed. Not valid password" 
            return 1
        fi
}

export change_password

function fix_chromium(){
  sudo -v
  echo "Locating Chromium profile"
  if [[ -d "/home/${CONFIG_USER}/snap/chromium/common/chromium" ]]; then
      CHROMIUM_PROFILE="/home/${CONFIG_USER}/snap/chromium/common/chromium"
  elif [[ -d "/home/${CONFIG_USER}/.config/chromium" ]]; then
      CHROMIUM_PROFILE="/home/${CONFIG_USER}/.config/chromium"
  else
      echo "Chromium profile directory not found"
      return 1
  fi

  sudo rm -rf ${CHROMIUM_PROFILE}/Singleton* > /dev/null 2>&1
  sudo rm -rf /home/${CONFIG_USER}/.cache/chromium > /dev/null 2>&1

}
export function fix_chromium


function fix_ipv4_netmask() {
    local input=$1
    ip="${input%%/*}"
    nm=''
    if [[ "$input" == *"/"* ]]; then
      nm="${input#*/}"
    fi
    if is_valid_ipv4 $ip > /dev/null 2>&1; then
      if is_valid_netmask $nm > /dev/null 2>&1; then
        echo "${ip}/${nm}"
      else
        echo "${ip}/24"
        return 2 # Invalid IP address format
      fi
    else
      echo ${input}
      return 1 # Invalid IP address format
    fi

    return 0 # Valid IP address
}
export -f fix_ipv4_netmask


function nls(){
  ls -l -a $1
}
export function nls




utilsn="${utilsn}
################################
### SYSTEM UTIL FUNCTIONS
################################
netlist = list network adapters and IP addresses
netliststatic = list network adapters and static IP addresses
netsetstatic = Select network adapter and set static_ip with provided IP like '192.168.179.103' or 'auto'
netsetauto = Select network adapter and set static_ip to auto'
netsetcustom = Select network adapter and enter a custom static IP address'
netsetnepi = Select network adapter and set static_ip to current NEPI_IP value'
pingi = Check connection to internet
pings = Check connection to Self IP address
pingn = Check connection to NEPI IP
pingnc = Ping NEPI IP address continously
nipa= Echo NEPI set IP address
naipa= Echo NEPI set IP alias addresses
nnipa= Echo NEPI set NTP IP addresses
nnet = Restart the network
ndhcp = Enable DHCP Internet Client
nclock = Sync clock
ninet = Restart network, connect to internet, and sync clock
nls = Run ls with -l -a for current folder, or pass FOLDER_PATH
check_passord = Check username and password combination
fix_chromium = Fix any Chromium config issues
fix_ipv4_netmask = Check valid IP and add 24 netmask if not provided
ubrc = Update and source the current user's bashrc files
sbrc = Source the current user's bashrc files" 

###################################
# File Util Functions
###################################

# Function to search for text
# Example call: find 'nepi_sdk.parse_header_msg'
function ftext(){
grep -r "$@" ./*
}
export -f ftext

# Function to search for text
# Example call: find 'nepi_sdk.parse_header_msg'
function ffile(){
find ./* -iname  "*$@*" 
}
export -f ffile

function update_text_value(){
  FILE=$1
  KEY=$2
  UPDATE=$3
  if [ -f "$FILE" ]; then
    if grep -q "$KEY" "$FILE"; then
      sed -i "/^$KEY/c\\$UPDATE" "$FILE"
    else
      echo -e "$UPDATE" | sudo tee -a $FILE
    fi
  else
    echo "File not found ${FILE}"
  fi
}
export -f update_text_value




function fix_path(){
  sudo -v
  if [[ ! -v "$1" && -n "$1" ]]; then
      target_path=$1
      if [[ ! -e "$target_path" ]]; then
        sudo mkdir -p $target_path
        sudo chmod 0664 ${target_path} > /dev/null 2>&1
      elif is_nepi_path $target_path; then
        echo "Fixing permissions for path: ${target_path}"
        sudo chown ${CONFIG_USER}:${CONFIG_USER} ${target_path} > /dev/null 2>&1
        if [[ ! -v "$2" && "$2" =~ ^[0-7]{3,4}$ ]]; then
          sudo chmod ${2} ${target_path} > /dev/null 2>&1
        fi

      else
          echo "NEPI Folder not found at ${target_path}"
          return 1
      fi
  else
    echo "No Path Provided"
    return 1
  fi
}
export -f fix_path

function fix_folder(){
  sudo -v
  if [[ ! -v "$1" && -n "$1" ]]; then
      target_path=$1
      if [[ ! -e "$target_path" ]]; then
        sudo chmod 0664 ${target_path} > /dev/null 2>&1
      elif is_nepi_path $target_path; then
        echo "Fixing permissions for path: ${target_path}"
        sudo chown -R ${CONFIG_USER}:${CONFIG_USER} ${target_path} > /dev/null 2>&1
        if [[ ! -v "$2" && "$2" =~ ^[0-7]{3,4}$ ]]; then
          sudo chmod -R ${2} ${target_path} > /dev/null 2>&1
        fi
      else
          echo "NEPI Folder not found at ${target_path}"
          return 1
      fi
  else
    echo "No Path Provided"
    return 1
  fi
}
export -f fix_folder


function fix_scripts(){
  sudo -v
  if [[ -v "$1" || -z "$1" ]]; then
    target_path=$(pwd)
  else
    target_path=$1
  fi
  if [[ -n "$target_path" ]]; then
    if [[ ! -e "$target_path" ]]; then
      sudo mkdir -p $target_path
    elif [[ ! -d "$target_path" ]]; then
      echo "Script path is not a found: ${target_path}"
      return 1
    fi

    if is_nepi_path $target_path; then
      echo "Fixing permissions in script folder: ${target_path}"
      sudo chown ${CONFIG_USER}:${CONFIG_USER} ${target_path}/* > /dev/null 2>&1
      sudo chmod 0776 ${target_path}/* > /dev/null 2>&1

    else
        echo "NEPI Script folder not found at ${target_path}"
        return 1
    fi
  else
    echo "No Script Path Provided"
    return 1
  fi
}
export -f fix_scripts





function update_yaml_value(){
    export UPDATE_YAML_KEY=$1
    #echo $UPDATE_YAML_KEY
    export UPDATE_YAML_VAL=$2
    #echo $UPDATE_YAML_VAL
    export UPDATE_YAML_FILE=$3
    #echo $UPDATE_YAML_FILE

    if [[ ${NEPI_MODE} == 'REMOTE' ]]; then
      eval_cmd="success=$(python3 ${BASH_FOLDER}/nepi_utils/update_yaml_value.py $UPDATE_YAML_KEY $UPDATE_YAML_VAL $UPDATE_YAML_FILE)"  #2>/dev/null"
      eval "$eval_cmd" 
      success=$(echo ${success})
      if [[ "$success" -ne 1 ]]; then
          echo "Success = ${success}"
          return 1
      fi
    else
      yq e -i '.'"$UPDATE_YAML_KEY"' = env(UPDATE_YAML_VAL)' $UPDATE_YAML_FILE
    fi
    eval "export $UPDATE_YAML_KEY=\"$UPDATE_YAML_VAL\""
}
export -f update_yaml_value


function update_json_value(){
    local JSON_FILE=$1
    local JSON_KEY=$2
    local JSON_VAL=$3
    if [ -z "$JSON_FILE" ] || [ -z "$JSON_KEY" ] || [ -z "$JSON_VAL" ]; then
        echo " KEY supports dot notation for nested keys, e.g. browser.show_home_button"
        return 1
    fi
    python3 ${BASH_FOLDER}/nepi_utils/update_json_value.py "$JSON_FILE" "$JSON_KEY" "$JSON_VAL"
}
export -f update_json_value


function sync_yaml_files(){
    SOURCE_FILE=$1
    TARGET_FILE=$2
    REPLACE_ENTRIES=0
    # if [[ -v "$3" ]]; then
    #   REPLACE_ENTRIES=$3
    # fi

    if [[ ! -f "$SOURCE_FILE" ]]; then
        echo "Source file does not exist: ${SOURCE_FILE}"
        return 1
    fi

    if [[ ! -f "$TARGET_FILE" ]]; then
        echo "Targetr file does not exist: ${TARGET_FILE}"
        target_path=$(dirname $TARGET_FILE)
        
        if fix_path $target_path; then
            sudo cp $SOURCE_FILE $TARGET_FILE
            fix_path $TARGET_FILE
            return 0
        elif [[ ! -d "$target_path" ]]; then
          echo "Failed to create path: ${target_path}"
          return 1
        fi
    fi

    eval_cmd="success=$(python3 ${BASH_FOLDER}/nepi_utils/sync_yaml_files.py $SOURCE_FILE $TARGET_FILE $REPLACE_ENTRIES)"  #2>/dev/null"
    eval "$eval_cmd" 
    success=$(echo ${success})
    

    if [[ "$success" -ne 1 ]]; then
        echo "Success = ${success}"
        return 1
    fi

}
export -f sync_yaml_files

clean_yaml_file() {
    local input_file="$1"
    if [[ -z "$input_file" ]]; then
        echo "Usage: remove_invalid_yaml_lines <filename>" >&2
        return 1
    fi

    # Use yq to re-parse and output the YAML, which filters invalid content
    # If the file is completely invalid, this command will fail.
    # The output is a new, valid YAML stream.
    if ! yq eval '.' "$input_file" > /dev/null; then
        echo "Error: Could not process the YAML file entirely. Check for major syntax errors." >&2
        return 1
    fi
}

# function clean_yaml_file(){
#     yaml_file=$1
#     #echo $yaml_file
#     if [ -f "$yaml_file" ]; then

#       success=0
#       eval_cmd="load_vals=$(python3 ${BASH_FOLDER}/nepi_utils/clean_yaml_file.py $tmp_file)"  #2>/dev/null"
#       eval "$eval_cmd"
      
#     else
#         echo "Yaml file not found ${yaml_file}"
#         return 1
#     fi
# }
# export -f clean_yaml_file

function load_yaml_file(){
    yaml_file=$1
    #echo $yaml_file
    if [ -f "$yaml_file" ]; then
    
      success=0
      clean_yaml_file $yaml_file
      eval_cmd="load_vals=$(python3 ${BASH_FOLDER}/nepi_utils/load_yaml_file.py $yaml_file)"  #2>/dev/null"
      eval "$eval_cmd"
      
      for entry in $load_vals; do
         export ${entry} 2> /dev/null
      done

      if [[ "$success" -ne 1 ]]; then
          echo "Success = ${success}"
          return 1
      fi

    else
        echo "Yaml file not found ${yaml_file}"
        return 1
    fi
}
export -f load_yaml_file

function print_yaml_file(){
    #echo $1
    yaml_file=$1
    if [ -f "$yaml_file" ]; then

      success=0
      eval_cmd="load_vals=$(python3 ${BASH_FOLDER}/nepi_utils/load_yaml_file.py $yaml_file)"  #2>/dev/null"
      eval "$eval_cmd"

      for entry in $load_vals; do
         export ${entry}
        if [[ "$entry" != *"success="* ]]; then
          echo ${entry}
        fi
      done

    if [[ "$success" -ne 1 ]]; then
        echo "Success = ${success}"
        return 1
    fi

    else
        echo "Yaml file not found ${yaml_file}"
        return 1
    fi
}
export -f print_yaml_file


function path_backup(){
    source_path=$1
    #echo $source_path
    backup_path=${1}.bak
    if [[ -n "$2" ]]; then
      backup_path=$2
    fi  
    #echo $backup_path

    overwrite=0
    if [[ -n "$3" ]]; then
      overwrite=$3
    fi
    #echo $overwrite

    if [[ -d "$source_path" || -f "$source_path" ]]; then
        if [[ -d "$source_path" ]]; then
          if find "$source_path" -maxdepth 0 -empty | read; then
            echo "Source folder is empty, nothing to backup ${source_path}"
            return 3
          elif [[ ! -d "${backup_path}" ]]; then
              echo "Creating  ${source_path} path copy at ${backup_path}"
              sudo mkdir -p ${backup_path}
              sudo cp -R -a ${source_path} ${backup_path}
          elif [[ -d "${backup_path}" && "overwrite" -eq 1 ]]; then
              echo "Copying ${source_path} to ${backup_path}"
              sudo rm -r $backup_path
              sudo cp -R -a $source_path $backup_path
          fi
        elif [[ -f "$source_path" ]]; then
          if [ ! -f "${backup_path}" ]; then
              echo "Creating  ${source_path} path copy at ${backup_path}"
              sudo cp -R -a ${source_path} ${backup_path}
          elif [[ -f "${backup_path}"  && "overwrite" -eq 1 ]]; then
            echo "Copying ${source_path} to ${backup_path}"
            sudo rm -r ${backup_path}
            sudo cp -R -a ${source_path} ${backup_path}
          fi
    
        else
          echo "Failed to backup path ${backup_path}"
          return 2
        fi
    else
      echo "Failed to find source path ${source_path}"
      return 1
    fi
    if [[ -d "$backup_path" || -f "$backup_path" ]]; then
        echo "Created ${source_path} path copy at ${backup_path}"
    else
        echo "Failed to backup path ${backup_path}"
        return 1
    fi
}
export -f path_backup


function path_sync(){
    source_path=$1
    target_path=$2
    delete=1
    if [[ -n "$3" ]]; then
    	delete=$3
    fi
    if [[ -d "$source_path" ]]; then
      if find "$source_folder" -maxdepth 0 -empty | read; then
          echo "Source folder is empty, nothing to sync ${source_folder}"
          return 3
      else
        if [[ ! -d "${target_path}" ]]; then
          echo "Creating target path ${target_path}"
          sudo mkdir -p ${target_path}
        fi
        if [[ -d "${target_path}" ]]; then
          echo "Syncing Folder ${source_path} to ${target_path}"
          if [[ "$delete" -eq 1 ]]; then
          	sudo rsync -avhr ${source_path}/ ${target_path}/ --delete
          else
          	sudo rsync -avhr ${source_path}/ ${target_path}/
          fi
        else
          echo "Failed to create target path ${target_path}"
          return 2
        fi
      fi
    elif [[ -f "$source_path" ]]; then
      echo "Syncing File ${source_path} to ${target_path}"
      sudo rsync -avhr ${source_path} ${target_path}
    elif [[ -L "$source_path" ]]; then
      echo "Syncing Symlink ${source_path} to ${target_path}"
      if [[ -d "${target_path}" ]]; then
          echo "Deleting existing target file ${target_path}"
          sudo rm ${target_path}
      fi
      echo "Copying Symlink ${source_path} to ${target_path}"
      sudo cp -a ${source_path} ${target_path}
    else
      echo "Failed to find source path ${source_path}"
      return 1
    fi
    echo echo "Sync complete ${source_path} to ${target_path}"
}
export -f path_sync

function path_delete(){
    source_path=$1
    if [[ ! -v "$source_path" || -z "$source_path" ]]; then
      source_path=$(pwd)
    fi
    if [[ -d "$source_path" || -f "$source_path" || -L "$source_path" ]]; then
          if is_nepi_path ${source_folder}; then
            echo "Deleting path ${source_folder}"
            sudo rm -r $source_path
          else
            return 1
          fi
    else
      echo "Path not found: ${source_path}"
      return 1
    fi
}
export -f path_delete

function path_usage(){
    source_path=$1
    if [[ -z "$source_path" ]]; then
      source_path=$(pwd)
    fi
    if is_valid_folder $source_path >/dev/null 2>&1; then
      cur_path=$(pwd)
      cd $source_path
      sudo ncdu
      cd $cur_path
    else
      echo "Not a valid path ${source_path}"
      return 1
    fi
}
export -f path_usage


function path_space_mb(){
    source_path=$1
    if [[ -z "$source_path" ]]; then
      source_path=$(pwd)
    fi
    if is_valid_folder $source_path >/dev/null 2>&1; then
      if space=$(sudo df -BM --output=avail "$source_path" | tail -n1 | sed 's/M//'); then
        avail_space=$space
      fi
    fi
    if [[ -n "$avail_space" ]]; then
      echo $avail_space
    else
      echo 0
      return 1
    fi
}
export -f path_space_mb


function path_space_gb(){
    source_path=$1
    if [[ -z "$source_path" ]]; then
      source_path=$(pwd)
    fi
    if [[ ! $source_path == /* ]]; then
      source_path=$(pwd)/${source_path}
    fi
    if is_valid_folder $source_path >/dev/null 2>&1; then
      if space=$(sudo df -BG --output=avail "$source_path" | tail -n1 | sed 's/M//'); then
        avail_space=${space%?}
      fi
    fi
    if [[ -n "$avail_space" ]]; then
      echo $avail_space
    else
      echo 0
      return 1
    fi
}
export -f path_space_gb

function path_size_kb(){
    source_path=$1
    if [[ -z "$source_path" ]]; then
      source_path=$(pwd)
    fi
    if [[ ! $source_path == /* ]]; then
      source_path=$(pwd)/${source_path}
    fi

    if is_valid_folder $source_path >/dev/null 2>&1; then
      path_size=$(sudo du -s "$source_path" | awk '{print $1}')
    fi
    if is_valid_file $source_path >/dev/null 2>&1; then
      path_size=$(sudo stat -c %s "$source_path")
      path_size=$((path_size / 1024))
    fi

    if [[ -n "$path_size" ]]; then
      path_size=$((path_size + 1))
      echo $path_size
    else
      echo 0
      return 1
    fi
}
export -f path_size_kb


function path_size_mb(){
    source_path=$1
    path_size=$(path_size_kb $source_path)
    
    if [[ -n "$path_size" ]]; then
      path_size=$((path_size / 1000))
      echo $path_size
    else
      echo 0
      return 1
    fi
}
export -f path_size_mb


function path_size_gb(){
    source_path=$1
    path_size=$(path_size_mb $source_path)

    if [[ -n "$path_size" ]]; then
      path_size=$((path_size / 1000))
      echo $path_size
    else
      echo 0
      return 1
    fi
}
export -f path_size_gb


function empty_trash(){
  trash-empty
  sudo rm -rf ${NEPI_HOME}.local/share/Trash/files/* >/dev/null 2>&1
}
export -f empty_trash


function select_file_from_folder() {
    local folder_path="$1"
    local selected_file=""

    # Check if the folder path is provided
    if [[ -z "$folder_path" ]]; then
        echo "Error: Please provide a folder path."
        return 1
    fi

    # Check if the folder exists
    if [[ ! -d "$folder_path" ]]; then
        echo "Error: Folder '$folder_path' not found."
        return 1
    fi

    # Change to the specified directory
    pushd "$folder_path" > /dev/null || return 1

    declare -a files
    for file in "$folder_path"/*; do
        if [[ -f "$file" ]]; then # Check if the item is a regular file
            filename=$(basename "$file")
            files+=( "$filename" ) # Add it to the array
            echo $filename
        fi
    done

    # Check if there are any files
    if [[ ${#files[@]} -eq 0 ]]; then
        popd > /dev/null
        return 1
    fi

    # Check if one file
    if [[ ${#files[@]} -eq 1 ]]; then
        echo "${files[0]}"
        popd > /dev/null
        return 0
    fi
    echo ""
    echo "Select a file from "${folder_path}":"
    echo "--------------------"
    echo ""
    select filename in "${files[@]}"; do
        if [[ -n "$filename" ]]; then
            selected_file="$filename"
            break
        else
            echo "Invalid selection. Please try again."
        fi
    done
    echo "You selected ${selected_file}"
    
    # Return to the original directory
    popd > /dev/null

    # Output the full path of the selected file
    if [[ -n "$selected_file" ]]; then
        echo "${selected_file}"
    fi
}
export -f select_file_from_folder

function run_script(){
  if [[ ! -v "$1" && -n "$1" ]]; then
    script_path=$1
    if [[ -f "$script_path" ]]; then
      echo "Running script $(basename $script_path)"
      bash ${script_path}
      script_error=$?
      if [[ "$script_error" -ne 0 ]]; then
        echo "Script $(basename $script_path) returned error ${script_error}"
        return $script_error
      fi
    else
        echo "Script not found at ${script_path}"
        return 1
    fi
  else
    echo "No Script Path Provided"
    return 1
  fi
}
export -f run_script

function source_script(){
  if [[ ! -v "$1" && -n "$1" ]]; then
    script_path=$1
    if [[ -f "$script_path" ]]; then
      echo "Sourcing script: ${script_path}"
      arg=$2
      if [[ -n $arg ]]; then
        echo "Passing arg ${arg}"
        source $script_path $arg
      else 
        echo "Passing no args"
        source ${script_path}
      fi
      script_error=$?
      if [[ "$script_error" -ne 0 ]]; then
        echo "Script $(basename $script_path) returned error ${script_error}"
        return $script_error
      fi
    else
        echo "Script not found at ${script_path}"
        return 1
    fi
  else
    echo "No Script Path Provided"
    return 1
  fi
}
export -f source_script




function process_count(){
  pname=$1
  pcount=$(ps aux | grep "${pname}" | grep -v grep | wc -l)
  echo $pcount
}
export -f process_count

function clean_tag_string(){
  cstring=$1
  cstring="${cstring// /_}"
  cstring="${cstring//-/_}"
  cstring="${cstring//./p}"
  cstring="${cstring,,}"
  echo $cstring
}
export -f clean_tag_string


function clean_version_string(){
  cstring=$1
  cstring="${cstring// /_}"
  cstring="${cstring//-/_}"
  cstring="${cstring//./p}"
  echo $cstring
}
export -f clean_version_string

function dev_version_string(){
  dstring=$(clean_version_string $1)
  dstring=${dstring}-$(date +%Y%m%d-%H%M)
  echo $dstring
}
export -f dev_version_string



function get_hw_type() {
  if is_valid_jetson >/dev/null 2>&1; then
      hw_type=jetson
  elif is_valid_arm64 >/dev/null 2>&1; then
      hw_type=arm64
  elif is_valid_amd64 >/dev/null 2>&1; then
      hw_type=amd64
  else
      hw_type=$(uname -m)
  fi
  echo $hw_type
}
export -f get_hw_type


function get_hw_arch() {
  if is_valid_jetson >/dev/null 2>&1; then
      hw_type=arm64
  elif is_valid_arm64 >/dev/null 2>&1; then
      hw_type=arm64
  elif is_valid_amd64 >/dev/null 2>&1; then
      hw_type=amd64
  else
      hw_type=$(uname -m)
  fi
  echo $hw_type
}
export -f get_hw_arch


function get_os_info() {
  sw_desc=''
  os_name=$(grep '^NAME=' /etc/os-release | cut -d'=' -f2 | tr -d '"')
  os_version=$(grep '^VERSION_ID=' /etc/os-release | cut -d'=' -f2 | tr -d '"')
  os_info="${os_name}${os_version}"
  echo $os_info
}
export -f get_os_info


function get_cuda_version(){

        if nvcc --version  >/dev/null 2>&1; then
          string=$(nvcc --version) 
          key=release
          value=$(echo "$string" | grep "${key}" | awk '{print $NF}' | cut -d'.' -f1-2)
          echo "${value#V}"
        else
          cuda_version=0
          cuda_path=/usr/local
          declare -a files
          for file in "$cuda_path"/*; do
              if [[ -d "$file" && "$file" == *cuda-* ]]; then # Check if the item is a regular file
                  cuda_version=${file##*-}
              fi
          done
          echo $cuda_version
        fi
}
export -f get_cuda_version


function get_openvpn_version(){
        if openvpn --version >/dev/null 2>&1; then
          value=$(openvpn --version 2>&1 | head -1 | awk '{print $2}')
          echo "${value}"
        else
          echo 0
        fi
}
export -f get_openvpn_version


function get_sw_desc() {
  os_desc=$(get_os_info)
  sw_desc=${os_desc}
  cuda_ver=$(get_cuda_version)
  if [[ "$cuda_ver" != '0' ]]; then
    sw_desc="${sw_desc}_CUDA${cuda_ver}"
  fi
  echo "${sw_desc}"
}
export -f get_sw_desc


function cmd_loop() {
  if [[ ! -v "$1" && -n "$1" ]]; then
    SECONDS=0
    while $1; do 
      echo "$SECONDS"
      sleep 1
    done
  else
    echo "No command string provided"
  fi
}
export -f cmd_loop



function create_ssh_key {
        sudo -v

        key_type=ed25519

        key_folder=$1
        if [[ -z $key_folder ]]; then
          key_folder=/home/${CONFIG_USER}/.ssh
        fi
        if [[ ! -d $key_folder ]]; then
          sudo mkdir -p $key_folder
        fi

        key_name=$2
        if [[ -z "$key_name" ]]; then
            key_name="nepi_$(hostname)_${CONFIG_USER}_ssh_key"
        fi 

        user_email=$3
        if [[ -z "$user_email" ]]; then
            user_email=${CONFIG_USER}@nepi.com
        fi     


        if [[ -d $key_folder ]]; then          

              key_file=${key_name}
              key_path=${key_folder}/${key_file}

              sudo chmod 0700 $key_folder
              sudo chown -R ${CONFIG_USER}:${CONFIG_USER} $key_folder

              if [[ -f $key_path ]]; then
                  echo "Key allready exists ${key_path}"
                  return 0
              fi

              ssh-keygen -t ${key_type} -f ${key_path} -q -N "" -C "${user_email}"
              eval "$(ssh-agent -s)"
              if ssh-add ${key_path} > /dev/null; then
                echo "Added key: ${key_file}"
                cat ${key_path}.pub
              else
                echo "Failed to add SSH key: ${key_file}"
              fi


              config_file=${key_folder}/config
              touch ${config_file}

              sudo chmod 0700 $key_folder
              sudo chmod 0600 $key_path
              sudo chown -R ${CONFIG_USER}:${CONFIG_USER} $key_folder



              if [[ -f $key_path ]]; then
                  echo "Created ssh_key ${key_file}"
                  echo "${key_path}"
                  return 0

              else
                echo "NEPI Failed to create ssh_key ${key_file}"
                return 1
              fi


        else
          echo "SSH Key folder not found ${key_folder}"
          return 2
        fi

}

export -f create_ssh_key



function add_ssh_key {
  sudo -v
  key_path=$1
  if [[ -n $key_path ]]; then

      # Output the full path of the selected file
      if [[ -f $key_path ]]; then
          if ssh-add ${key_path} > /dev/null; then
              echo "Added SSH key: ${key_path}"
          else
            echo "Failed to add SSH key: ${key_path}"
            return 3
          fi

          sudo chmod 0700 $key_path
          sudo chown -R ${CONFIG_USER}:${CONFIG_USER} $key_path

          return 0
      else
        echo "File not found at key path: ${key_path}"
        return 2
      fi
  else
    echo "No Key Path Provided"
    return 1
  fi



}

export -f add_ssh_key


function select_ssh_key {
        sudo -v
        key_folder=$1
        if [[ -z $key_folder ]]; then
          key_folder="/home/${CONFIG_USER}/.ssh"
        fi
        sel_ssh_file=''
        echo "Checking for available key options in folder: ${key_folder}"

        if [[ -d $key_folder ]]; then
                ###############
                #echo "Checking for available key options"
                # Change to the specified directory
                sudo chmod 0700 $key_folder
                sudo chown -R ${CONFIG_USER}:${CONFIG_USER} $key_folder

                pushd "$key_folder" > /dev/null || return 1

                declare -a files
                for file in "$key_folder"/*; do
                    pub_file="${file}.pub"
                    #echo "Checking file: ${file}"
                    #echo "Looking for public key file: ${pub_file}"
                    filename=$(basename "$file")
                    if [[ -f "$file" ]]; then # Check if the item is a regular file
                        if [[ -f $pub_file ]]; then
                          files+=( "$filename" ) # Add it to the array
                          echo $filename
                        fi
                    fi
                done
                sudo chmod 0700 $key_folder
                

                # Check if there are any files
                if [[ ${#files[@]} -eq 0 ]]; then
                    echo "No SSH Key files found in folder: ${key_folder}"
                    popd > /dev/null
                    return 1
                fi

                # # Check if one file
                # if [[ ${#files[@]} -eq 1 ]]; then
                #     echo "${files[0]}"
                #     popd > /dev/null
                #     return 0
                # fi
                echo ""
                echo "Select a file from "${folder_path}":"
                echo "--------------------"
                echo ""
                select filename in "${files[@]}"; do
                    if [[ -n "$filename" ]]; then
                        sel_ssh_file="$filename"
                        break
                    else
                        echo "Invalid selection. Please try again."
                    fi
                done
                
                # Return to the original directory
                popd > /dev/null

                # Output the full path of the selected file
                if [[ -n "$sel_ssh_file" ]]; then
                    sel_ssh_path=${key_folder}/$sel_ssh_file
                    add_ssh_key $sel_ssh_path
                    return $?
                else
                  return 2
                fi

        else
          echo "SSH Key folder not found ${key_folder}"
          return 1
        fi

}

export -f select_ssh_key



#### Update Help Test
utilsn="${utilsn}
################################
### NEPI SYSTEM UTIL FUNCTIONS
################################
ftext = Find text in files recursively
ffile = Find filenames with text match recursively
cmd_loop = Runs the COMMAND_STRING until Ctrl-C every second
update_text_value = Adds or Replaces value in text file given FILE KEY UPDATE_STRING FILE
update_yaml_value = Update entry in yaml file given KEY VAL FILE
update_json_value = Update entry in json file given FILE KEY VAL. KEY supports dot notation for nested keys (e.g. browser.show_home_button)
print_yaml_file = Prints all of the yaml entries in given FILE
sync_yaml_files = Sync missing keys between given SOURCE_FILE TARGET_FILE. Add '1' to replace existing values 
load_yaml_file = Exports all of the yaml entries to system variables in given FILE
path_backup = Backup SOURCE_PATH TARGET_PATH with safe checks. Optional 0 or 1 to overwrite if exists. 
path_sync = Sync SOURCE_PATH to TARGET_PATH with safe checks. Optional 0 or 1 to delete files.
select_file_from_folder = Selection menu of files in provided SOURCE_PATH.  Echos selected path name
fix_path = Update file or folder owner to 1000 at provided FIX_PATH, and update access permissions with PERM_NUMBER if provided.
fix_folder = Update or Make folder and contents with owner to 1000 for provided FIX_PATH, and update access permissions with PERM_NUMBER if provided.
fix_scripts = Update files in provided FIX_PATH (or current path if not provided) with owner 1000 and +x access permissions.
path_delete = Deletes TARGET_PATH with safe checks
path_usage = Analyze provided path for usage
path_space_mb = Echos available MB space for SOURCE_PATH. Echos 0 if path not vald folder
path_space_gb = Echos available GB space for SOURCE_PATH. Echos 0 if path not vald folder
path_size_kb = Echos size of path (file or folder) in KB space for SOURCE_PATH. Echos 0 if path not vald folder
path_size_mb = Echos size of path (file or folder) in MB space for SOURCE_PATH. Echos 0 if path not vald folder
path_size_gb = Echos size of path (file or folder) in GB space for SOURCE_PATH. Echos 0 if path not vald folder
empty_trash = Empty Trash for current User
run_script = Uses 'bash' to run script at provided SCRIPT_PATH
source_script = Uses 'source' to run script at provided SCRIPT_PATH, with an optional SCRIPT_OPTION passed to script
process_count = Echos number of processes running for provide PROCESS_NAME
clean_tag_string = Echos a NEPI Info formated version of the provided STRING
clean_version_string = Echos a NEPI Version formated version of the provided VERSION_STRING
dev_version_string = Echos a NEPI Dev Version formated version of the provided VERSION_STRING
get_hw_type = Echos the current hardware type string (ie. jetson, arm64, amd64, or uname)
get_hw_arch = Echos the current hardware arch string (ie. arm64, amd64, or uname)
get_os_info = Echos the current OS NameVersion
get_cuda_version = Echos CUDA version number if nvcc --version availble or 0
get_openvpn_version = Echos OpenVPN version number if openvpn installed or 0
get_sw_desc = Echos NEPI formated software vesion tag
add_ssh_key = Add the ssh key in the provided full path ssh_key file
create_ssh_key = Create a new SSH key key pair in provided key_folder
select_ssh_key = Select SSH key from available keys in provided key_folder"






###################################
# Command Line Confi Util Functions
###################################


head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
  export PS1="\u@\h \[\e[32m\]\w \[\e[91m\]\$(parse_git_branch)\[\e[00m\]$ "

  #GIT Command Line Branch Display
  parse_git_branch() {
      git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
  }
fi

###################################
# ROS Util Functions
###################################
NROS=${NEPI_BASE}/nepi_engine/setup.bash
ROS=/opt/ros/noetic/setup.bash
HAS_ROS=$(dpkg -l | grep ros-)
if [ 1 ]; then # [[ -z "$HAS_ROS" ]]; then

    export NEEDS_ROS=1

    # Function to search for topic containing string
    function sros(){
      # Source ROS Env
      if [[ -f "$NROS" ]]; then
        echo "Sourcing ros bash ${NROS}"
        source ${NROS}
      elif [[ -f "$ROS" ]]; then
        echo "Sourcing ros bash ${ROS}" 
        source ${ROS}
      else
        echo "No Ros Setup File Found"
      fi
      export NEEDS_ROS=0
    }

    export -f sros

    # Function to search for topic containing string
    function ftopic(){
    if [ "$NEEDS_ROS" -eq 1 ]; then
      sros
      wait
    fi
    rostopic list | grep "$@" 
    }

    # Function to print all topics out
    function ltopics(){
    if [ "$NEEDS_ROS" -eq 1 ]; then
      sleep 1 & sros
      wait
    fi
    rostopic list
    }

    # Function to listen to topic
    function etopic(){
    if [ "$NEEDS_ROS" -eq 1 ]; then
      sleep 1 & sros
      wait
    fi
    rostopic echo "$@" 
    }

    # Function to search for service containing string
    function fservice(){
    if [ "$NEEDS_ROS" -eq 1 ]; then
      sleep 1 & sros
      wait
    fi
    rosservice list | grep "$@" 
    }

    # Function to print all services out
    function lservices(){
    if [ "$NEEDS_ROS" -eq 1 ]; then
      sleep 1 & sros
      wait
    fi
    rosservice list
    }

    # to call service
    function cservice(){
    if [ "$NEEDS_ROS" -eq 1 ]; then
      sleep 1 & sros
      wait
    fi
    rosservice call "$@"
    }

utilsn="${utilsn}
###########################
### NEPI ROS UTIL FUNCTIONS
###########################
sros = source ros bash setup
snros = source nepi ros bash setup
ltopics = List all active topics
ftopic = Find topics containing provided string
etopic = Echo to provided topic
lservices = List all active services
fservice = Find services containing provided string
cservice = Call service"

fi

###################################
# Docker Util Functions
###################################

if which docker &> /dev/null; then
  function dimg(){
    sudo docker images
  }

  function dps(){
    sudo docker ps -a
  }

  
utilsn="${utilsn}
###########################
### Docker UTIL FUNCTIONS
###########################
dimg = sudo docker images
dps = sudo docker ps -a"

fi

###################################
# NEPI Dev Functions
###################################

GREEN='\033[0;32m'
RED='\033[0;31m'

alias nepihome="
cd ${NEPI_HOME}"


alias nsetup="cd $(NSETUP)/scripts"


function nepirui() {
  if [[ -n "$DISPLAY" ]]; then
    if [[ ${NEPI_MODE} != 'SYSTEM' ]]; then
      rui_ip=$(NRUI_IP)
      echo "Will Connect to NEPI RUI at: ${rui_ip}"
      if [[ ${NEPI_MODE} == 'REMOTE' ]]; then
        if ! pingn; then
          return
        fi
      fi
      
      if command -v chromium-browser &>/dev/null; then
                chromium-browser http://${rui_ip}:5003/
      else
          # Check for an alternative common name if the first one fails
          if command -v chromium &>/dev/null; then
                chromium http://${rui_ip}:5003/
          else
              echo "Chromium Browser not Installed"
              echo "INSTALL WITH: sudo snap install chromium"
          fi
      fi
    fi
  else
    echo "No Display Detected"
  fi

}

export -f nepirui


function nepistorage() {
  sudo -v
  if [[ ${NEPI_MODE} == 'REMOTE' ]]; then
    if pingn; then
      shdrive=/mnt/nepi_share_storage
      if [[ ! -d $shdrive ]]; then
          sudo mkdir $shdrive
      fi
      sudo chown ${CONFIG_USER}:${CONFIG_USER} $shdrive
      if ! mountpoint -q $shdrive; then
        sudo mount.cifs //${NEPI_IP}/nepi_storage $shdrive -o user=$NEPI_USER
      fi
      if mountpoint -q $shdrive; then
        cd $shdrive
        return 0
      else
        echo "Failed to mount and connect nepi shared folder: ${shdrive}"
        return 1
      fi
    else
        return 1
    fi
  else
    shdrive=/mnt/nepi_config
    if [[ -d $shdrive ]]; then
      cd $shdrive
      return 0
    else
      echo "Failed to mount and connect nepi shared folder: ${shdrive}"
      return 1
    fi
  fi
}

export -f nepistorage

function nepistorageopen() {
  sudo -v
  if nepistorage; then
      xdg-open $shdrive
  fi
}

export -f nepistorageopen


function nepiconfig() {
  sudo -v

  if [[ ${NEPI_MODE} == 'REMOTE' ]]; then
    if pingn; then
      shdrive=/mnt/nepi_share_config
      if [[ ! -d $shdrive ]]; then
          sudo mkdir $shdrive
      fi
      sudo chown ${CONFIG_USER}:${CONFIG_USER} $shdrive
      if ! mountpoint -q $shdrive; then
        sudo mount.cifs //${NEPI_IP}/nepi_config $shdrive -o user=$NEPI_ADMIN_USER
      fi
      if mountpoint -q $shdrive; then
        cd $shdrive
        return 0
      else
        echo "Failed to mount and connect nepi shared folder: ${shdrive}"
        return 1
      fi
    else
        return 1
    fi
  else
    shdrive=/mnt/nepi_config
    if [[ -d $shdrive ]]; then
      cd $shdrive
      return 0
    else
      echo "Failed to mount and connect nepi shared folder: ${shdrive}"
      return 1
    fi
  fi
}

export -f nepiconfig

function nepiconfigopen() {
  sudo -v
  if nepiconfig; then
      xdg-open $shdrive
  fi
}

export -f nepiconfigopen


function nepisync {

    # Sync SSH Keys
    echo ""
    echo "Syncing NEPI System Config Files"
    cur_folder=$(pwd)
    if nepiconfig 2> /dev/null ; then
        NEPI_CONFIG_SOURCE="$(pwd)/system_cfg/etc/nepi_system_config.yaml"
        NEPI_CONFIG_DEST=/home/${CONFIG_USER}/nepi_system_config.yaml
        echo "Copying NEPI SYSTEM CONFIG from: ${NEPI_CONFIG_SOURCE}  to ${NEPI_CONFIG_DEST}"
        if [ -f $NEPI_CONFIG_SOURCE ]; then
            sudo cp -p ${NEPI_CONFIG_SOURCE} ${NEPI_CONFIG_DEST}
            source $(pwd)/system_cfg/etc/load_system_config.sh
        else
          echo "NEPI SYSTEM CONFIG file not found at: ${NEPI_CONFIG_SOURCE} "
        fi
    else
      echo "Failed to connect to NEPI CONFIG"
    fi


    # Sync SSH Keys
    echo ""
    echo "Syncing SSH Keys"

    NEPI_SSH_KEYS_SOURCE=${RESOURCES_FOLDER}/etc/ssh/ssh_keys
    NEPI_SSH_KEYS_DEST=/home/${CONFIG_USER}/.ssh


    if [[ ! -d "$NEPI_SSH_KEYS_DEST" ]]; then
        mkdir -p $NEPI_SSH_KEYS_DEST
    fi
    # Sync keys with nepi system config key folder

    

    if [ -d $NEPI_SSH_KEYS_SOURCE ]; then
        echo "Copying NEPI SSH Keys from: ${NEPI_SSH_KEYS_SOURCE} to ${NEPI_SSH_KEYS_DEST}"
        sudo cp -p ${NEPI_SSH_KEYS_SOURCE}/*nepi_* ${NEPI_SSH_KEYS_DEST}/
    fi
 
    if nepiconfig 2> /dev/null; then
        NEPI_SSH_KEYS_SHARE="$(pwd)/system_cfg/etc/ssh/ssh_keys"
        if [ -d $NEPI_SSH_KEYS_SHARE ]; then
            if [[ ${NEPI_MODE} == 'HOST' ]]; then
              echo "Copying NEPI SSH Keys from: ${NEPI_SSH_KEYS_DEST} to ${NEPI_SSH_KEYS_SHARE}"
              sudo cp -p ${NEPI_SSH_KEYS_DEST}/*nepi_* ${NEPI_SSH_KEYS_SHARE}/
              echo "Copying NEPI SSH Keys from: ${NEPI_SSH_KEYS_SHARE} to ${NEPI_SSH_KEYS_DEST}"
              sudo cp -p ${NEPI_SSH_KEYS_SHARE}/*nepi_* ${NEPI_SSH_KEYS_DEST}/
            else
              echo "Copying NEPI SSH Keys from: ${NEPI_SSH_KEYS_SHARE} to ${NEPI_SSH_KEYS_DEST}"
              sudo cp -p ${NEPI_SSH_KEYS_SHARE}/*nepi_* ${NEPI_SSH_KEYS_DEST}/
              echo "Copying NEPI SSH Keys from: ${NEPI_SSH_KEYS_DEST} to ${NEPI_SSH_KEYS_SHARE}"
              sudo cp -p ${NEPI_SSH_KEYS_DEST}/*nepi_* ${NEPI_SSH_KEYS_SHARE}/
            fi
        else
          echo "NEPI SYSTEM SSH folder not found at: ${NEPI_SSH_KEYS_SHARE} "
        fi
    else
      echo "Failed to connect to NEPI CONFIG"
    fi


    sudo chmod 0700 $NEPI_SSH_KEYS_DEST
    sudo chmod 0600 $NEPI_SSH_KEYS_DEST/*
    sudo chown -R ${CONFIG_USER}:${CONFIG_USER} $NEPI_SSH_KEYS_DEST/*

    cd $cur_folder

}

export -f nepisync


function nepisetkey {
    sudo -v

    key_file=$1

    if [[ -z $key_file ]]; then
      key_file=$NEPI_SSH_KEY_FILE
    fi
    key_folder="/home/${CONFIG_USER}/.ssh"
    key_path="${key_folder}/${key_file}"

    if [[ ! -f $key_path ]]; then
      echo "Private Key not found at ${key_path}"
      return 1
    fi

    pub_path="${key_path}.pub"
    if [[ ! -f $pub_path ]]; then
      echo "Public Key not found at ${pub_path}"
      return 2
    fi

    sudo chmod 0700 $key_folder
    sudo chmod 0600 $key_path
    sudo chown -R ${CONFIG_USER}:${CONFIG_USER} $key_folder

    if ssh-add ${key_path} > /dev/null; then
      echo "Added key: ${key_file}"
      cat ${key_path}.pub
      export NEPI_SSH_KEY=$key_file
      echo "NEPI SSH Key updated to key file ${NEPI_SSH_KEY_FILE}"
    else
      echo "Failed to add SSH key: ${key_file}"
    fi



    return 0

}

export -f nepisetkey


function nepisshkey {
    sudo -v

    setkey=$1

    key_folder="/home/${CONFIG_USER}/.ssh"

    if [[ ! -d $key_folder ]]; then
      sudo mkdir -p $key_folder
    fi    

    PS3=$'\n'"Please enter your choice by NUMBER: "
    options=(  "Select SSH Key" "Create SSH Key")

    while true; do
        #clear # Optional: Clear the screen before displaying the menu

        COLUMNS=1
        select opt in "${options[@]}" ; do
            case $opt in

                "Select SSH Key")
                    ret=$(select_ssh_key $key_folder)
                    sel_error=$?
                    sel_file=$(echo $ret | awk '{print $NF}')
                    #echo "Got select SSH Key file error: ${sel_error}"
                    if [[ $sel_error -eq 0 && -n sel_file ]]; then
                      echo ''
                      echo "Got selected SSH Key file: ${sel_file}"
                      key_path=$sel_file
                      exist_key='yes'
                      break 2 # Exit both the select and the while loop
                    else
                      echo ''
                      echo "No SSH Key files found in folder: ${key_folder}"
                      echo ''
                    fi     
                    break # Exit the select statement
                    ;;
                "Create SSH Key")
                    key_email='nepi@numurus'
                    key_name="nepi_$(hostname)_${CONFIG_USER}_ssh_key"
                    key_path="${key_folder}/key_name"
                    if [[ -f $key_path ]]; then
                      echo "NEPI SSH Key with name allready exists: ${key_name}"
                      check_key=$(ask_yes_no "Do you want to replace this key?")
                      if [[ ${check_key} == 'yes' ]]; then
                        sudo rm -r ${key_path}*
                      else
                        key_path=''
                        break
                      fi

                    fi

                    ret=$(create_ssh_key $key_folder $key_name $key_email)
                    sel_error=$?
                    sel_file=$(echo $ret | awk '{print $NF}')
                    #echo "Got select SSH Key file error: ${sel_error}"
                    
                    if [[ $? -eq 0 && -n sel_file ]]; then
                      echo ''
                      echo "Got New SSH Key file: ${sel_file}"
                      key_path=$sel_file
                      break 2 # Exit both the select and the while loop
                    fi     
                    break # Exit the select statement
                    ;;
                *)
                    echo "Invalid option, please try again."
                    ;;
            esac
        done
    done
    echo ""

    if [[ -n $key_path ]]; then
      key_name=$(basename "$key_path")
      ret_val=0
      if [[ $setkey -eq 1 ]]; then

        nepisetkey $key_name
        ret_val=$?
      fi

      if [[ $ret_val -eq 0 ]]; then

         echo $key_name
         return 0
      else
          echo "NEPI SSH Key FAILED TO SET"
         echo ''
         return 2
      fi

    else
        echo "NEPI SSH Key NOT CHANGED"
         echo ''
         return 1
    fi



}

export -f nepisshkey


function nepiauthrm {
    sudo -v
    key_file=$1

    
    if [[ -n $key_file ]]; then

        key_folder=$NEPI_SSH_FOLDER
        key_path=${key_folder}/${key_file}

        if [[ -f $key_path ]]; then

          sudo chmod 0700 $key_folder
          sudo chown -R ${CONFIG_USER}:${CONFIG_USER} $key_folder

          authorized_keys_path="${key_folder}/authorized_keys"
          touch ${authorized_keys_path}

          key_pub=$(cat ${key_path}.pub)
          key_email="${key_pub##* }"
          echo "Removing existing key for id ${key_email}"
          if [[ -n $key_email ]]; then   
            sudo chmod 0777 $authorized_keys_path
            echo "Editing file ${authorized_keys_path}"   
            sed -i "/$key_email/d" "$authorized_keys_path"
          fi

          systemctl&> /dev/null
          res=$?
          if [[ "$res" -eq 0 ]];  then
            sudo systemctl restart sshd
          fi

          supervisorctl&> /dev/null
          res=$?
          if [[ "$res" -eq 0 ]];  then
            sudo supervisorctl restart sshd
          fi

          return 0
          
        else
          echo "Remove Key File Not Found: ${key_path}"
          return 1
        fi

    else
        echo "Remove Key File Not Provided"
        return 1
    fi
}

export -f nepiauthrm


function nepiauthadd {
    sudo -v
    key_file=$1

    
    if [[ -n $key_file ]]; then

        key_folder=$NEPI_SSH_FOLDER
        key_path=${key_folder}/${key_file}

        if [[ -f $key_path ]]; then

          sudo chmod 0700 $key_folder
          sudo chown -R ${CONFIG_USER}:${CONFIG_USER} $key_folder

          authorized_keys_path="${key_folder}/authorized_keys"
          if [[ -f $authorized_keys_path ]]; then
            sudo rm $authorized_keys_path
          fi
          touch ${authorized_keys_path}

          key_pub=$(cat ${key_path}.pub)
          key_email="${key_pub##* }"
          echo "Removing existing key for id ${key_email}"
          if [[ -n $key_email ]]; then     
            sudo chmod 0777 $authorized_keys_path
            echo "Editing file ${authorized_keys_path}"   
            sed -i "/$key_email/d" "$authorized_keys_path"
          fi

          echo "Adding key ${key_file}"
          sudo cat ${key_path}.pub >> $authorized_keys_path
          echo "Autherized Key file Updated"

          sudo chmod 0700 $key_folder
          sudo chmod 0600 $authorized_keys_path
          sudo chmod 0600 $key_path
          sudo chmod 0600 $key_pub
          sudo chown -R ${CONFIG_USER}:${CONFIG_USER} $key_folder

          systemctl&> /dev/null
          res=$?
          if [[ "$res" -eq 0 ]];  then
            sudo systemctl restart sshd
          fi

          supervisorctl&> /dev/null
          res=$?
          if [[ "$res" -eq 0 ]];  then
            sudo supervisorctl restart sshd
          fi

          return 0
          
        else
          echo "Add Key File Not Found: ${key_path}"
          return 1
        fi

    else
        echo "Add Key File Not Provided"
        return 1
    fi
}

export -f nepiauthadd



function nepigithub {
    sudo -v
    key_folder="/home/${CONFIG_USER}/.ssh"

    if [[ ! -d $key_folder ]]; then
      sudo mkdir -p $key_folder
    fi    

    if is_valid_internet >/dev/null 2>&1; then

        echo " "
        echo "################################# "
        echo "Checking Github SSH Key"
        echo ""


        needs_key='yes'
        exist_key='no'
        add_key='no'
        ghub_email=''

        while [[ "$needs_key" == 'yes' ]]; do


            if ! is_valid_internet >/dev/null 2>&1; then
                echo "NO INTERNET CONNECTION DETECTED.  "
                echo ""
                needs_key=$(ask_yes_no "Do you want to connect to internet and try again?")
            else
                ssh -T git@github.com >/dev/null 2>&1
                if [[ "$?" -lt 2 ]]; then
                    key_path=$(ssh -G git@github.com 2>/dev/null | grep -im1 '^IdentityFile' | cut -d' ' -f2) >/dev/null
                    key_name=$(basename "$key_path")
                    needs_key='no'
                else
                    key_path=''
                    echo ""
                    echo "NO VALID GITHUB SSH KEY FOUND"
                    echo ""

                    PS3=$'\n'"Please enter your choice by NUMBER: "
                    options=(  "Select SSH Key" "Create SSH Key")

                    while true; do
                        #clear # Optional: Clear the screen before displaying the menu

                        COLUMNS=1
                        select opt in "${options[@]}" ; do
                            case $opt in

                                "Select SSH Key")
                                    ret=$(select_ssh_key $key_folder)
                                    sel_error=$?
                                    sel_file=$(echo $ret | awk '{print $NF}')
                                    #echo "Got select SSH Key file error: ${sel_error}"
                                    if [[ $sel_error -eq 0 && -n sel_file ]]; then
                                      echo ''
                                      echo "Got selected SSH Key file: ${sel_file}"
                                      key_path=$sel_file
                                      exist_key='yes'
                                      break 2 # Exit both the select and the while loop
                                    else
                                      echo ''
                                      echo "No SSH Key files found in folder: ${key_folder}"
                                      echo ''
                                    fi     
                                    break # Exit the select statement
                                    ;;
                                "Create SSH Key")
                                    key_path=''
                                    echo "Creating NEPI GitHub ssh_key ${key_file}"
                                    echo ""

                                    while [[ -z "$ghub_email" ]]; do
                                        read -p "Enter your GitHub email address: " USER_INPUT
                                        if is_valid_email "$USER_INPUT"; then
                                            echo "Using email ${USER_INPUT}"
                                            ghub_email=$USER_INPUT
                                        else
                                            echo "Not A Valid Email"
                                            return 1
                                        fi  
                                    done   
                                        

                                    

                                    key_name="$(hostname)_${CONFIG_USER}_github"
                                    ret=$(create_ssh_key $key_folder $key_name $ghub_email)
                                    sel_error=$?
                                    sel_file=$(echo $ret | awk '{print $NF}')
                                    #echo "Got select SSH Key file error: ${sel_error}"
                                    
                                    if [[ $? -eq 0 && -n sel_file ]]; then
                                      echo ''
                                      echo "Got selected SSH Key file: ${sel_file}"
                                      key_path=$sel_file
                                      break 2 # Exit both the select and the while loop
                                    elif [[ $? -eq 1 ]]; then
                                      echo ''
                                      echo "SSH Github Key for this user allready exists: ${key_name}"
                                      check_key=$(ask_yes_no "Do you want to use this key?")
                                      if [[ ${check_key} == 'yes' ]]; then
                                        key_path=$sel_file
                                        break 2 # Exit both the select and the while loop
                                      fi
                                    fi     
                                    break # Exit the select statement
                                    ;;
                                *)
                                    echo "Invalid option, please try again."
                                    ;;
                            esac
                        done
                    done
                    echo ""







                    if [[ -n $key_path ]]; then

                        sudo chmod 0700 $key_folder
                        sudo chown -R ${CONFIG_USER}:${CONFIG_USER} $key_folder

                        config_file=/home/${CONFIG_USER}/.ssh/config
                        touch ${config_file}
                        if grep -qnw $config_file -e ${key_name}; then
                            : #echo "Already Done"
                        else
                            
                            NAME=$(echo "$ghub_email" | sed -E 's/"?([^"]+)"? <.*>/\1/')

                            echo 'Host github.com' | sudo tee -a $config_file
                            echo '   AddKeysToAgent yes' | sudo tee -a $config_file
                            echo '   IdentityFile '${key_path} | sudo tee -a $config_file
                            echo ''


                        fi

                        sudo chmod 0700 $key_folder
                        sudo chmod 0600 $key_path
                        sudo chown -R ${CONFIG_USER}:${CONFIG_USER} $key_folder
                        needs_key='no'
                        add_key='yes'

                        break 2 # Exit both the select and the while loop
                        
                    fi

                fi

            fi
        done

        if [[ -n $key_path && ${add_key} == 'yes' ]]; then
            key_name=$(basename "${key_path}")


                ssh -T git@github.com >/dev/null 2>&1
                if [[ "$?" -gt 1 ]]; then

                    echo "*** ADD YOUR NEW NEPI GITHUB SSH KEY TO YOUR GITHUB ACCOUNT BEFORE PROCEEDING ***"
                    echo ""
                    echo "1) Log Into Your GitHub Account at www.github.com"
                    echo "2) Click on your User Icon, and select 'Settings"
                    echo "3) Select 'SSH and GPG keys' from the left sidebar menu"
                    echo "4) Click the 'New SSH key' button in the top right"
                    echo "5) Enter the following information in the boxes provided,"
                    echo "   Then click the 'Add SSH key' button"
                    echo ""
                    echo "<< TITLE >>"
                    echo ${key_name}
                    echo ""
                    echo "<< KEY_TYPE >>"
                    echo "Authentication Key"
                    echo ""
                    echo "<< KEY >>"
                    echo $(sudo cat ${key_path}.pub)
                    echo ""
                    echo "6) Rerun this script to test that your GitHub SSH Key Authenticates"

                    echo ""
                    read -p "Press enter after configuring your GitHub account with new ssh key"

              fi

        fi

        g_email=$(git config user.email)
        g_name=$(git config user.name)

        if [[ -z $g_email || -z $g_name ]]; then
          if [[ -z $ghub_email ]]; then
                              while [[ -z "$ghub_email" ]]; do
                                  read -p "Enter your GitHub email address: " USER_INPUT
                                  if is_valid_email "$USER_INPUT"; then
                                      echo "Using email ${USER_INPUT}"
                                      ghub_email=$USER_INPUT
                                  else
                                      echo "Not A Valid Email"
                                      return 1
                                  fi  
                              done   
          fi

          if [[ -n $ghub_email ]]; then
                  ghub_name=$(echo "$ghub_email" | sed -E 's/"?([^"]+)"? <.*>/\1/')
                  git config --global user.email "$ghub_email"
                  git config --global user.name "$ghub_name"
          
          fi
        fi



        ssh -T git@github.com >/dev/null 2>&1
        if [[ "$?" -lt 2 ]]; then
            echo ''
            echo '#######################'
            echo "GitHub SSH Key authenticated with key file ${key_path}"
            echo '#######################'
            echo ''



            # nepi_repo_address=$NEPI_REPO_ADDRESS_DEFAULT
            # echo ""
            # PS3=$'\n'"Please enter your choice by NUMBER: "
            # options=(  "Use Default NEPI Repo" "Fork Default NEPI Repo" "Set Custom NEPI Repo")

            # while true; do
            #     #clear # Optional: Clear the screen before displaying the menu

            #     COLUMNS=1
            #     select opt in "${options[@]}" ; do
            #         case $opt in

            #             "Use Default NEPI Repo")
            #                 NEPI_REPO_ADDRESS=$nepi_repo_address
            #                 break 2 # Exit both the select and the while loop

            #                 ;;
            #             "Fork Default NEPI Repo")
            #                  NEPI_REPO_ADDRESS=$nepi_repo_address
            #                 break 2 # Exit both the select and the while loop

            #                 ;;
            #             "Set Custom NEPI Repo")
            #                 NEPI_REPO_ADDRESS=$nepi_repo_address
            #                 break 2 # Exit both the select and the while loop

            #                 ;;
            #             *)
            #                 echo "Invalid option, please try again."
            #                 ;;
            #         esac
            #     done
            # done
            # echo ""

            nepi_repo_name=$(basename "${NEPI_REPO_ADDRESS%.*}")
            if [[ -n $NEPI_REPO_ADDRESS && -n $nepi_repo_name ]]; then
              export NEPI_REPO_ADDRESS=$NEPI_REPO_ADDRESS
              export NEPI_REPO_NAME=$nepi_repo_name

              update_text_value $NEPI_BASH_UTILS "export NEPI_REPO_ADDRESS=" "export NEPI_REPO_ADDRESS=${NEPI_REPO_ADDRESS}"


              echo "Using NEPI Repo ${nepi_repo_name}"
              echo ""
   
              nepi_repo_folder="/home/${CONFIG_USER}/${nepi_repo_name}"
              if [[ ! -d $nepi_repo_folder ]]; then
                echo "Cloning NEPI Repo to ${nepi_repo_folder}"
                echo "" 
                nepiclone
              fi

            fi



            echo " "
            echo "################################# "
            echo "NEPI DEV GITHUB SETUP COMPLETE"
            echo "################################# "
            echo " "


        else
            echo "GitHub SSH Key NOT AUTHENTICATED"
            echo "Fix errors and try again"
        fi

    fi

}

export -f nepigithub


function nepiclone {
  if is_valid_internet ; then
    cd ~/
    git clone ${NEPI_REPO_ADDRESS} 
    if [[ $? -eq 0 ]]; then
      cd ${NEPI_REPO_NAME}
      git checkout main
      git submodule update --init --recursive
    else
      echo "Failed to clone NEPI Repo from ${NEPI_REPO_ADDRESS}"
    fi
  fi
}

export -f nepiclone

function nepiclonedev {
  if is_valid_internet ; then
    cd ~/
    git clone ${NEPI_REPO_ADDRESS} 
    if [[ $? -eq 0 ]]; then
      cd ${NEPI_REPO_NAME}
      git checkout develop
      git submodule update --init --recursive 
    else
      echo "Failed to clone NEPI Repo from ${NEPI_REPO_ADDRESS}"
    fi
  fi
}

export -f nepiclonedev


function pulln {
  if is_valid_internet ; then
    repo_folder=/home/${CONFIG_USER}/${NEPI_REPO_NAME}
    if [[ -d ${repo_folder} ]]; then
      cd $repo_folder
      git pull --recurse-submodules
      git submodule foreach --recursive "git checkout main && git pull origin main" 2> /dev/null
    fi
  fi
}

export -f pulln






## NEPI deploy complete
alias nepidpl="
cd $NEPI_REPO_FOLDER
source ./deploy_nepi_complete.sh"

# NEPI deploy repos
alias repodpl="
cd $NEPI_REPO_FOLDER
source ./deploy_nepi_repos.sh"

function gitmain {
  git checkout main
  git pull
}

function pushn(){
  cur_path=$(pwd)
  cur_folder=${PWD##*/}
  # IFS='/' read -r -a path_parts <<< "$cur_path"
  # if [[ ${#path_parts[@]} -lt 4 ]]; then
  #     echo "Current folder is not in the NEPI Repo folder: ${cur_path}"
  #     return 1
  # fi
  # third_folder="${path_parts[3]}"
  # if [[ ${third_folder} != ${NEPI_REPO_NAME} ]]; then
  #     echo "Current folder is not in the NEPI Repo folder: ${cur_path}"
  #     return 1
  # fi
  git add --all
  git commit -m "*$@*" 
  git push >/dev/null 2>&1

  par_path=$(dirname "$(pwd)")
  par_folder=$(basename "$par_path")
  #echo $cur_folder
  #echo $par_folder
  head_name=$(git rev-parse --abbrev-ref HEAD >/dev/null 2>&1)
  if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
    if [[ ("$(pwd)" == "${NEPI_REPO_FOLDER}"  || "$(pwd)" == "${NEPI_REPO_FOLDER}/src") ]]; then
        echo -e "${GREEN}Pushing to repo ${PWD##*/} Head develop"
        git push origin HEAD:develop

    else
        echo -e "${GREEN}Pushing to repo ${PWD##*/} Head main"
        git push origin HEAD:main
        #git checkout main
    fi
    if [ ! $? -eq 0 ]; then
      echo -e "${RED}Push Failed"
      return 1 # Failed
    fi
    echo -e "${GREEN}Push Successfully"
  else
    echo -e "${RED}Not in Git Repo"
  fi
}


## NEPI deploy complete
function nepisetup_remote() {
sudo -v
skip_software=1
source $(NSETUP)/scripts/remote_env_setup.sh $skip_software
source /home/${CONFIG_USER}/.bashrc
}

function nepisetup_host() {
sudo -v
source $(NSETUP)/scripts/docker_bash_setup.sh
source /home/${CONFIG_USER}/.bashrc
echo "Running NEPI Setup in NEPI_MODE: ${NEPI_MODE}"
SHOW_CONFIG_MENU=1
echo ${SHOW_CONFIG_MENU}
source ${NEPI_SYSTEM_CONFIG}/etc/nepi_system_config.sh ${SHOW_CONFIG_MENU}
source /home/${CONFIG_USER}/.bashrc
}

function nepisetup_system() {
sudo -v
source $(NSETUP)/scripts/nepi_bash_setup.sh
source /home/${CONFIG_USER}/.bashrc
SHOW_CONFIG_MENU=1
echo ${SHOW_CONFIG_MENU}
source ${NEPI_SYSTEM_CONFIG}/etc/nepi_system_config.sh ${SHOW_CONFIG_MENU}
source /home/${CONFIG_USER}/.bashrc
}


function nepisetup() {
sudo -v
nepi_mode=${NEPI_MODE}
echo "NEPI_MODE: ${nepi_mode}"
if [[ ${nepi_mode} == 'REMOTE' ]]; then 
  nepisetup_remote
elif [[ ${nepi_mode} == 'HOST' ]]; then 
  nepisetup_host
elif [[ ${nepi_mode} == 'SYSTEM' ]]; then 
  nepisetup_system
fi
}






utilsn="${utilsn}
################################
### NEPI Dev FUNCTIONS
################################
nepisetup_remote = Setup the current NEPI environment MODE as REMOTE
nepisetup_host = Setup the current NEPI environment MODE as HOST
nepisetup_system = Setup the current NEPI environment MODE as SYSTEM
nepimode = Echo the current NEPI environment MODE
nepisetup = Run the environment setup script for the current NEPI environment MODE
nepihome = Change to users home folder
nepirui = Open Chromium to NEPI RUI Dashboard page
nsetup = Change Dir to the NEPI setup scripts folder
nepirui = Open Chromium to RUI Dashboard page
nepistorage = Change dir to NEPI shared Storage Drive if accessable
nepistorageopen = Open file manager to NEPI shared Storage Drive if accessable
nepiconfig = Change dir to NEPI shared Config Drive if accessable
nepiconfigopen = Open file manager to NEPI shared Config Drive if accessable
nepisync = Sync NEPI SSH Key files
nepisetkey = Set provided key name as NEPI device key
nepisshkey = NEPI SSH key setup function
nepiauthadd = Add provide key name to SSH authorized_key file
nepiauthrm = Remove provide key name from SSH authorized_key file
nepigithub = Check and Setup a GitHub SSH key for your GitHub account
nepiclone = Clone the latest NEPI source-code repo
nepiclonedev = Clone the latest NEPI Development branch source-code repo
pulln = Update to the latest NEPI source-code repo
nepidpl = Deploy nepi complete to nepi device
gitmain = Change to main branch in current repo or submodule folder
pushn = Add,commit,push repo changes with optional comment msg in current repo or submodule folder"







export UTILSN=${utilsn}



