#!/bin/bash

##
## Copyright (c) 2024 Numurus, LLC <https://www.numurus.com>.
##
## This file is part of nepi-engine
## (see https://github.com/nepi-engine).
##
## License: 3-clause BSD, see https://opensource.org/licenses/BSD-3-Clause
##

# This file contains nepi docker host system aliases and sources nepi bash utils

#echo "########################"
#echo "NEPI Docker Aliases"
#echo "########################"


export NEPI_HOME=/home/nepihost

export NEPI_BASE=/opt/nepi

export NEPI_STORAGE=/mnt/nepi_storage

export NEPI_DOCKER_CONFIG=/mnt/nepi_config/docker_cfg
export NEPI_STORAGE=/mnt/nepi_storage

NEPI_UTILS_FILE=/home/nepihost/.nepi_bash_utils

source $NEPI_UTILS_FILE


########################
# Help Msg Initialization
#########################
HELPN="${UTILSN}"


###################################
# NEPI DEV Util Functions
###################################
export SOURCE_FOLDER=/home/${USER}/nepi_engine_ws
GREEN='\033[0;32m'
RED='\033[0;31m'


## NEPI deploy complete
alias nepihome="
cd ${NEPI_HOME}"

alias nhome="
cd ${NEPI_HOME}"

## NEPI deploy complete
alias nepidpl="
cd $SOURCE_FOLDER
./deploy_nepi_complete.sh"

# NEPI deploy repos
alias repodpl="
cd $SOURCE_FOLDER
./deploy_nepi_repos.sh"

utilsn="${utilsn}
### NEPI DEV UTIL FUNCTIONS
nepidpl = deploy nepi complete
repodpl = deploy specific repos"

function pushn(){
  git add --all
  git commit -m "*$@*" 
  git push >/dev/null 2>&1
  cur_folder=${PWD##*/}
  par_path=$(dirname "$(pwd)")
  par_folder=$(basename "$par_path")
  #echo $cur_folder
  #echo $par_folder
  head_name=$(git rev-parse --abbrev-ref HEAD) >/dev/null 2>&1
  if [ "$?" -eq 0 ]; then #$(is_git_repo $PWD) -eq 1 ]; then
    if [[ "$cur_folder" == 'nepi_engine_ws' || "$par_folder" == 'nepi_engine_ws' ]]; then
        echo -e "${GREEN}Pushing to repo ${PWD##*/} Head develop"
        git push origin HEAD:develop

    else
        echo -e "${GREEN}Pushing to repo ${PWD##*/} Head main"
        git push origin HEAD:main
    fi
    if [ ! $? -eq 0 ]; then
      echo -e "${RED}Push Failed"
      return 1 # Failed
    fi
    echo -e "${GREEN}Push Successfully"
  else
    echo -e "${RED}Not in Git Repo"
  fi
}





HELPN="${HELPN}
################################
### NEPI DEV UTIL FUNCTIONS
################################
nhome = Switch to Home folder
nepidpl = Deploy nepi complete to nepi device
repodpl = Deploy repos to nepi device
pushn = Add,commit,push repo changes with provided comment"


#############################
# NEPI SHORTCUT FUNCTIONS
#############################

export NEPI_USER=nepi
export NEPI_HOME=/home/nepi

export NEPI_DOCKER_CONFIG='/mnt/nepi_config/docker_cfg'
export NEPI_STORAGE=/mnt/nepi_storage

# NEPI stop and start shortcuts
function nepistop(){
   sudo systemctl stop nepi_docker
   bash ${NEPI_DOCKER_CONFIG}/nepi_docker_stop.sh
}
export -f nepistop

function nepistart(){
     bash ${NEPI_DOCKER_CONFIG}/nepi_docker_start.sh
}
export -f nepistart

function nepidev(){
     bash ${NEPI_DOCKER_CONFIG}/nepi_docker_dev.sh
}
export -f nepidev



function nepilogin(){
   nuser=$1
   bash ${NEPI_DOCKER_CONFIG}/nepi_docker_login.sh  $nuser    
}
export -f nepilogin

function nepiloginroot(){
  nuser=root
  bash ${NEPI_DOCKER_CONFIG}/nepi_docker_login.sh $nuser 
}
export -f nepiloginroot



function nepicommit(){
   commit_desc=$1
   bash ${NEPI_DOCKER_CONFIG}/nepi_docker_commit.sh $commit_desc
}
export -f nepicommit



function nepiswitch(){
   bash ${NEPI_DOCKER_CONFIG}/nepi_docker_switch.sh
}
export -f nepiswitch


function nepiinit(){
  import_path=/mnt/nepi_storage/nepi_images
  if [[ -n "$1" ]]; then
    if [[ -f "$1" ]]; then
      image_path=$1
    elif [[ -n "$2" ]]; then
      image_path=${import_path}/${$2}
    fi
  fi

  if [[ -d "$import_path" ]]; then
        image_count=$(sudo docker images --format "{{.Repository}}:{{.Tag}}" | wc -l)
        if [ "$image_count" -gt 0 ]; then
          echo "WARNING: IF YOU PROCEED, ALL EXISTING NEPI IMAGES WILL BE STOPPED AND REMOVED"
          echo ""
          response=$(ask_yes_no "Do you want to proceed?")
        else
            response=yes
        fi

        if [ "$response" == "yes" ]; then
          
          selected=$(select_file_from_folder $import_path | tail -n1)
          if [[ -n "$selected" ]]; then
            echo "Initializing with NEPI Image file ${selected}"
            image_path="${import_path}/${selected}"
          else
              echo "No NEPI Image Files Found in: ${import_path}"
              return 1
          fi  
        else
            echo "Action cancelled."
            return 1
        fi  
  fi

  if [[ -f "$image_path" ]]; then
    bash ${NEPI_DOCKER_CONFIG}/nepi_docker_init.sh $image_path
  else
      echo "No NEPI Image Files Found in: ${import_path}"
      return 1
  fi  
  
}
export -f nepiinit


function nepiimport(){
  import_path=/mnt/nepi_storage/nepi_images
  if [[ -n "$1" ]]; then
    if [[ -f "$1" ]]; then
      image_path=$1
    elif [[ -n "$2" ]]; then
      image_path=${import_path}/${$2}
    fi
  fi

  if [[ -d "$import_path" ]]; then
      selected=$(select_file_from_folder $import_path | tail -n1)
      echo "Selected NEPI Image file ${selected}"
      if [[ -n "$selected" ]]; then
        echo "Importing NEPI Image file ${selected}"
        image_path="${import_path}/${selected}"
      else
          echo "No NEPI Image Files Found in: ${import_path}"
          return 1
      fi  
  fi
  echo "Calling NEPI Import script with file ${image_path}"
  if [[ -f "$image_path" ]]; then
    bash ${NEPI_DOCKER_CONFIG}/nepi_docker_import.sh $image_path
  else
      echo "No NEPI Image Files Found in: ${import_path}"
      return 1
  fi  
}
export -f nepiimport


function nepipull(){
  pull_ref=$1
  echo "Pulling NEPI Image from ${pull_ref}"
  bash ${NEPI_DOCKER_CONFIG}/nepi_docker_pull.sh $pull_ref
}
export -f nepipull

function nepiretag(){
  sw_desc=$1
  echo "Retagging NEPI Active Image with ${sw_desc}"
  bash ${NEPI_DOCKER_CONFIG}/nepi_docker_retag.sh $sw_desc
}
export -f nepipull


function nepiexport(){
  bash ${NEPI_DOCKER_CONFIG}/nepi_docker_export.sh $1
}
export -f nepiexport


function nepisave(){
  bash ${NEPI_DOCKER_CONFIG}/nepi_docker_save.sh $1
}
export -f nepisave


function nepiload(){
  import_path=/mnt/nepi_storage/nepi_images
  if [[ -n "$1" ]]; then
    if [[ -f "$1" ]]; then
      image_path=$1
    elif [[ -n "$2" ]]; then
      image_path=${import_path}/${$2}
    fi
  fi

  if [[ -d "$import_path" ]]; then
      selected=$(select_file_from_folder $import_path | tail -n1)
      echo "Selected NEPI Image file ${selected}"
      if [[ -n "$selected" ]]; then
        echo "Importing NEPI Image file ${selected}"
        image_path="${import_path}/${selected}"
      else
          echo "No NEPI Image Files Found in: ${import_path}"
          return 1
      fi  
  fi
  echo "Calling NEPI Load script with file ${image_path}"
  if [[ -f "$image_path" ]]; then
    bash ${NEPI_DOCKER_CONFIG}/nepi_docker_load.sh $image_path
  else
      echo "No NEPI Image Files Found in: ${import_path}"
      return 1
  fi  
}
export -f nepiload






function nepiconfig(){
  SHOW_CONFIG_MENU=1
  bash /mnt/nepi_config/system_cfg/etc/nepi_system_config.sh $SHOW_CONFIG_MENU
}
export -f nepiconfig

function nepiupdate(){
  bash /mnt/nepi_config/system_cfg/etc/nepi_system_config.sh
}
export -f nepiupdate

function nepistatus(){
  sudo systemctl status nepi_docker
}
export -f nepistatus

function nepilogs(){
  sudo journalctl -u nepi_docker -f
}
export -f nepilogs


# NEPI stop and start shortcuts
function nepienable(){
   sudo systemctl enable nepi_docker
   echo "NEPI Docker Service enabled on next boot"
}
export -f nepienable

function nepidisable(){
    sudo systemctl disable nepi_docker
    echo "NEPI Docker Service disabled on next boot"
}
export -f nepidisable

function nepireset(){
  bash /opt/nepi/etc/scripts/sync_to_configs.sh
}
export -f nepireset


function nepirestart(){
   sudo systemctl restart nepi_docker
}
export -f nepirestart

function nepiupdate() {
  bash ${NEPI_DOCKER_CONFIG}/nepi_docker_update.sh
}
export -f nepiupdate

function nepisettings(){
  echo "NEPI DOCKER SETTINGS"
  echo "--------------------"
  print_config_file /mnt/nepi_config/docker_cfg/nepi_docker_config.yaml
  echo ""
  echo "NEPI SYSTEM SETTINGS"
  echo "--------------------"
  print_config_file /mnt/nepi_config/docker_cfg/nepi_docker_config.yaml
}
export -f nepiconfig

HELPN="${HELPN}
################################
## NEPI Docer Shortcut Functions ##
################################
nepistart = Start the NEPI docker container
nepidev = Start the NEPI docker container in a dev mode with no processes running
nepistop = Stop the running NEPI docker container
nepilogin = Log into the running NEPI container as user 'nepi'
nepiloginroot = Log into the running NEPI container as user 'root'
nepiswitch = Switch to Inactive NEPI container on next boot or reststat
nepicommit = Commit the running NEPI container
nepiinit = Reset, clear, and import new NEPI Image
nepiimport = Import a NEPI image .tar file. Optional: Enter a file name or full file path.
nepiexport = Export the running NEPI container to a .tar file. Enter a file name or full file path.
nepiload = Import a NEPI image .archive.tar file. Optional: Enter a file name or full file path.
nepisave = Save the active NEPI Image with all commits to a .archieve.tar file. Enter a file name or full file path.
nepipull = Import a NEPI image from a remote repository given the PULL_URL.
nepitag = Update the Software Description field in the active NEPI container
nepiconfig = Configure NEPI System settings
nepiupdate = Reconfigure NEPI System settings using the stored System Config settings file
nepienable = Enable NEPI Docker service on next boot
nepidisable = Disable NEPI Docker service on next boot
nepirestart = Restart NEPI docker service
nepistatus = Show the systemctl status for nepi_docker service
nepilogs = Show live NEPI Docker service journal file
nepireset = Reset all NEPI Config Folders
nepiupdate = Run update process on NEPI Docker config file
nepisettings = Print current NEPI DOCKER and SYSTEM configuration settings"



###################################
#NEPI folder shortcuts
#echo "Setting up NEPI Folder Shortcuts"
export AI="/mnt/nepi_storage/ai_models"
export AIF="/opt/nepi/nepi_engine/share/nepi_ai_ifs"
export API="/opt/nepi/nepi_engine/lib/python3/dist-packages/nepi_api"
export APPS="/opt/nepi/nepi_engine/share/nepi_apps"
export AUTO="/mnt/nepi_storage/automation_scripts"
export BUILD="/mnt/nepi_storage/nepi_src/nepi_engine_ws"

export AUTO="/mnt/nepi_storage/automation_scripts"
export DATA="/mnt/nepi_storage/data"
export DIST="/opt/nepi/nepi_engine/lib/python3/dist-packages"
export DRIVERS="/opt/nepi/nepi_engine/lib/nepi_drivers"
export ETC="/opt/nepi/nepi_engine/etc"
export INSTALL="/mnt/nepi_storage/intstall"
export LAUNCH="/opt/nepi/nepi_engine/share/nepi_env/launch"
export LIB="/opt/nepi/nepi_engine/lib"
export LIBSDK="/opt/nepi/nepi_engine/lib/nepi_sdk"
export MANAGERS="/opt/nepi/nepi_engine/lib/nepi_managers"
export NEPI="/opt/nepi"
export NFI="/mnt/nepi_storage/nepi_full_img"
export NFIA="/mnt/nepi_storage/nepi_full_img_archive"
export NIMG="/mnt/nepi_storage/nepi_images"
export ENGINE="/opt/nepi/nepi_engine"
export RUI="/opt/nepi/nepi_rui/src/rui_webserver/rui-app/src"
export RUI_ENV="/opt/nepi/nepi_rui"
export SCRIPTS="/opt/nepi/scripts"
export SETUPN="/mnt/nepi_storage/nepi_src/nepi_engine_ws/nepi_setup/scripts"
export SDK="/opt/nepi/nepi_engine/lib/python3/dist-packages/nepi_sdk"
export SHARE="/opt/nepi/nepi_engine/share"
export SRC="/mnt/nepi_storage/nepi_src/nepi_engine_ws/src"
export SRCRUI="/mnt/nepi_storage/nepi_src/nepi_engine_ws/src/nepi_engine/nepi_rui/src/rui_webserver/rui-app/src"
export TMP="/mnt/nepi_storage/tmp"
export TRAIN="/mnt/nepi_storage/ai_training"
export DRIVE="/mnt/nepi_storage"

export DCFG="/mnt/nepi_config/docker_cfg"
export FCFG="/mnt/nepi_config/factory_cfg"
export SCFG="/mnt/nepi_config/system_cfg"
export UCFG="/mnt/nepi_storage/user_cfg"


# NEPI navigation shortcuts

alias ai="cd $AI"
alias aif="cd $AIF"
alias api="cd $API"
alias apps="cd $APPS"
alias auto="cd $AUTO"
alias data="cd $DATA"
alias dist="cd $DIST"
alias drivers="cd $DRIVERS"
alias etc="cd $ETC"
alias intstall="cd $INSTALL"
alias launch="cd $LAUNCH"
alias lib="cd $LIB"
alias libsdk="cd $LIBSDK"
alias managers="cd $MANAGERS"
alias nepi="cd $NEPI"
alias nfi="cd $NFI"
alias nfia="cd $NFIA"
alias nimg="cd $NIMG"
alias engine="cd $ENGINE"
alias rui="cd $RUI"
alias rui_env="cd $RUI_ENV"
alias scripts="cd $SCRIPTS"
alias setupn="cd $SETUPN"
alias sdk="cd $SDK"
alias share="cd $SHARE"
alias src="cd $SRC"
alias srcrui="cd $SRCRUI"
alias tmp="cd $TMP"
alias train="cd $TRAIN"
alias drive="cd $DRIVE"

alias dcfg="cd $DCFG"
alias fcfg="cd $FCFG"
alias scfg="cd $SCFG"
alias ucfg="cd $UCFG"


export NSETUP="/home/${USER}/nepi_setup/scripts"
alias nsetup="cd ${NSETUP}"

export NDSETUP="/mnt/nepi_config/docker_cfg"
alias ndsetup="cd ${NDSETUP}"

alias nfw="cat /opt/nepi/nepi_engine/etc/fw_version.txt"

HELPN="${HELPN}
################################
## NEPI folder shortcuts ##
################################
ai = /mnt/nepi_storage/ai_models
auto = /mnt/nepi_storage/automation_scripts
data = /mnt/nepi_storage/data
intstall = /mnt/nepi_storage/intstall
nfi = /mnt/nepi_storage/nepi_full_img
nfia = /mnt/nepi_storage/nepi_full_img_archive
nimg = /mnt/nepi_storage/nepi_images
src = /mnt/nepi_storage/nepi_src/nepi_engine_ws/src
srcrui = /mnt/nepi_storage/nepi_src/nepi_engine_ws/src/nepi_engine/nepi_rui/src/rui_webserver/rui-app/src
tmp = /mnt/nepi_storage/tmp
train = /mnt/nepi_storage/ai_training
drive = /mnt/nepi_storage

dcfg = /mnt/nepi_config/docker_cfg
fcfg = /mnt/nepi_config/factory_cfg
scfg = /mnt/nepi_config/factory_cfg
ucfg = /mnt/nepi_storage/user_cfg

nsetup = /home/${USER}/nepi_setup/scripts
ndsetup = /mnt/nepi_config/docker_config

nfw = Show Installed NEPI FW Version"

# Print out the nepi shortcuts
function nepihelp(){
    echo "$HELPN"
}

export NEPI_REMOTE_SETUP=0
export NEPI_TARGET_SRC_DIR=${NEPI_STORAGE}/nepi_src



