#!/bin/bash

##
## Copyright (c) 2024 Numurus <https://www.numurus.com>.
##
## This file is part of nepi setup tools (nepi_setup) repo
## (see https://github.com/nepi-engine/nepi_setup)
##
## License: nepi setup tools are licensed under the "Numurus Software License", 
## which can be found at: <https://numurus.com/wp-content/uploads/Numurus-Software-License-Terms.pdf>
##
## Redistributions in source code must retain this top-level comment block.
## Plagiarizing this software to sidestep the license obligations is illegal.
##
## Contact Information:
## ====================
## - mailto:nepi@numurus.com
##

# This file contains NEPI system aliases and sources NEPI bash utils

#echo "########################"
#echo "NEPI System Aliases"
#echo "########################"
if [[ ! -n $CONFIG_USER ]]; then
    CONFIG_USER=$(id -un)
    if [[ ${CONFIG_USER} == 'root' ]]; then
        CONFIG_USER=$SUDO_USER
    fi
fi
if [[ ! -n $CONFIG_USER ]]; then
    id -nu 1000
fi

export NEPI_MODE='SYSTEM'
NEPI_UTILS_FILE=/home/${CONFIG_USER}/.nepi_bash_utils
source $NEPI_UTILS_FILE
export NEPI_MODE='SYSTEM'

################################
export NEPI_REMOTE_SETUP=0
################################

HELPN="${UTILSN}"

#############################
# NEPI SYSTEM FUNCTIONS
#############################
GREEN='\033[0;32m'
RED='\033[0;31m'


alias nepihome="
cd ${NEPI_HOME}"

alias nhome="
cd ${NEPI_HOME}"


# NEPI stop and start shortcuts
function nepistop(){
  sudo -v

  service_name="nepi_engine"
  if systemctl status > /dev/null 2>&1; then
    if systemctl is-active --quiet "$service_name.service" ; then
      sudo systemctl stop "$service_name"
    fi
  elif supervisorctl status > /dev/null 2>&1; then
    #echo "Supervisor and its managed processes appear to be running."
    status = supervisorctl status "$service_name" 2>/dev/null
    if echo "$status" | grep -q "RUNNING"; then
      sudo supervisorctl stop nepi_engine
    fi
  fi

  sudo ${NEPI_BASE}/scripts/nepi_engine_stop

}

export -f nepistop


function nepistart(){
    sudo -v
    nepistop
    source ${NEPI_BASE}/scripts/nepi_engine_start
}

export -f nepistart


function nepistartc(){
    sudo -v
    nepistop
    echo "Cleaning NEPI SSH Folders"
    system_source_config="${NEPI_SYSTEM_CONFIG}/ssh_keys"
    sudo rm -r $system_source_config
    source ${NEPI_BASE}/scripts/nepi_engine_start
}

export -f nepistartc

## NEPI build shortcuts

function nepibld(){
  sudo -v
  run_folder=$(pwd)
  nepistop
  echo "Cleaning NEPI ETC Folders"
  sudo rm -r ${NEPI_BASE}/etc/*
  sudo rm -r ${NEPI_BASE}/docker_cfg/*
  sudo rm -r ${NEPI_BASE}/docker
  cd $NEPI_BUILD_REPO_FOLDER
  source ./build_nepi_complete.sh
  sbrc
  cd $run_folder
}

function nepibldc(){
  sudo -v
  run_folder=$(pwd)
  nepistop
  echo "Cleaning NEPI ETC Folders"
  sudo rm -r ${NEPI_BASE}/etc/*
  sudo rm -r ${NEPI_BASE}/nepi_engine/etc/*
  sudo rm -r ${NEPI_BASE}/nepi_engine/lib/*
  sudo rm -r ${NEPI_BASE}/nepi_rui/src/rui_webserver/rui-app/src/*
  
  sudo rm -r ${NEPI_BASE}/docker_cfg/*
  sudo rm -r ${NEPI_BASE}/docker
  sudo rm -r /mnt/nepi_config/system_cfg/*
  echo "Cleaning NEPI SSH Folders"
  system_source_config="${NEPI_SYSTEM_CONFIG}/ssh_keys"
  sudo rm -r $system_source_config
  sudo rm -r /home/nepi/.ssh/*
  cd $NEPI_BUILD_REPO_FOLDER
  source ./build_nepi_complete.sh
  sbrc
  cd $run_folder
}


# NEPI build shortcuts
function codebld(){
sudo -v
run_folder=$(pwd)
cd $NEPI_BUILD_REPO_FOLDER
source ./build_nepi_code.sh
cd $run_folder
}

# NEPI build shortcuts
function ruibld(){
  sudo -v
  run_folder=$(pwd)
  cd $NEPI_BUILD_REPO_FOLDER
  source ./build_nepi_rui.sh
  cd $run_folder
}


function snvm(){
  echo ' ' | sudo tee -a $BASHRC
  echo '##### NVM Config #####' | sudo tee -a $BASHRC
  echo 'export NVM_DIR='/home/nepi'/.nvm' | sudo tee -a $BASHRC
  echo '[ -s ${NVM_DIR}/nvm.sh ] && \. ${NVM_DIR}/nvm.sh' | sudo tee -a $BASHRC
  echo '[ -s ${NVM_DIR}/bash_completion ] && \. ${NVM_DIR}/bash_completion' | sudo tee -a $BASHRC
}
export -f snvm

function nepistatus(){
  sudo supervisorctl status
}
export -f nepistatus

function nepistatus_engine(){
  sudo supervisorctl tail nepi_engine
}
export -f nepistatus_engine

function nepistatus_rui(){
  sudo supervisorctl tail nepi_rui
}
export -f nepistatus_rui

function nepistatus_license(){
  sudo supervisorctl tail nepi_license
}
export -f nepistatus_license

function nepistatus_ssh(){
  sudo supervisorctl tail nepi_ssh
}
export -f nepistatus_ssh


HELPN="${HELPN}
################################
### NEPI SYSTEM UTIL FUNCTIONS
################################
nepihome = Change to NEPI home dir
nepistart = Start the NEPI processes
nepistartc = Clear SSH folders and Start the NEPI processes
nepistop = stop the NEPI processe
nepibld = Build NEPI bash, config, code repos, and RUI
nepibldc = Clear SSH folders and Build complete
codebld = Build NEPI code repos only
ruibld = Build the RUI only
nepistatus = Print running status of all NEPI processes
nepistatus_engine = Print tail of nepi_engine process
nepistatus_rui = Print tail of nepi_rui process
nepistatus_license = Print tail of nepi_license process
nepistatus_ssh = Print tail of nepi_ssh process"



###################################
#NEPI folder shortcuts
#echo "Setting up NEPI Folder Shortcuts"
export AI="${NEPI_STORAGE}/ai_models"
export AIF="${NEPI_BASE}/nepi_engine/share/nepi_ai_ifs"
export API="${NEPI_BASE}/nepi_engine/lib/python3/dist-packages/nepi_api"
export APPS="${NEPI_BASE}/nepi_engine/share/nepi_apps"
export AUTO="${NEPI_STORAGE}/automation_scripts"
export BUILD=$NEPI_BUILD_REPO_FOLDER

export AUTO="${NEPI_STORAGE}/automation_scripts"
export DATA="${NEPI_STORAGE}/data"
export DIST="${NEPI_BASE}/nepi_engine/lib/python3/dist-packages"
export DRIVERS="${NEPI_BASE}/nepi_engine/lib/nepi_drivers"
export ETC="${NEPI_BASE}/nepi_engine/etc"
export INSTALL="${NEPI_STORAGE}/intstall"
export LAUNCH="${NEPI_BASE}/nepi_engine/share/nepi_env/launch"
export LIB="${NEPI_BASE}/nepi_engine/lib"
export LIBSDK="${NEPI_BASE}/nepi_engine/lib/nepi_sdk"
export MANAGERS="${NEPI_BASE}/nepi_engine/lib/nepi_managers"
export NEPI="${NEPI_BASE}"
export NFI="${NEPI_STORAGE}/nepi_full_img"
export NFIA="${NEPI_STORAGE}/nepi_full_img_archive"
export NIMG="${NEPI_STORAGE}/nepi_images"
export ENGINE="${NEPI_BASE}/nepi_engine"
export RUI="${NEPI_BASE}/nepi_rui/src/rui_webserver/rui-app/src"
export RUI_ENV="${NEPI_BASE}/nepi_rui"
export SCRIPTS="${NEPI_BASE}/scripts"
export SETUPN="${NEPI_STORAGE}/nepi_src/${NEPI_BUILD_REPO_NAME}/nepi_setup/scripts"
export SDK="${NEPI_BASE}/nepi_engine/lib/python3/dist-packages/nepi_sdk"
export SHARE="${NEPI_BASE}/nepi_engine/share"
export SRC="${NEPI_STORAGE}/nepi_src/${NEPI_BUILD_REPO_NAME}/src"
export SRCRUI="${NEPI_STORAGE}/nepi_src/${NEPI_BUILD_REPO_NAME}/src/nepi_engine/nepi_rui/src/rui_webserver/rui-app/src"
export TMP="${NEPI_STORAGE}/tmp"
export TRAIN="${NEPI_STORAGE}/ai_training"
export DRIVE="${NEPI_STORAGE}"

export FCFG="${NEPI_FACTORY_CONFIG}"
export SCFG="${NEPI_SYSTEM_CONFIG}"
export DCFG="${NEPI_DOCKER_CONFIG}"
export UCFG="${NEPI_STORAGE}/user_cfg"


# NEPI navigation shortcuts

alias ai="cd $AI"
alias aif="cd $AIF"
alias api="cd $API"
alias apps="cd $APPS"
alias auto="cd $AUTO"
alias data="cd $DATA"
alias dist="cd $DIST"
alias drivers="cd $DRIVERS"
alias etc="cd $ETC"
alias intstall="cd $INSTALL"
alias launch="cd $LAUNCH"
alias lib="cd $LIB"
alias libsdk="cd $LIBSDK"
alias managers="cd $MANAGERS"
alias nepi="cd $NEPI"
alias nfi="cd $NFI"
alias nfia="cd $NFIA"
alias nimg="cd $NIMG"
alias engine="cd $ENGINE"
alias rui="cd $RUI"
alias rui_env="cd $RUI_ENV"
alias scripts="cd $SCRIPTS"
alias setupn="cd $SETUPN"
alias sdk="cd $SDK"
alias share="cd $SHARE"
alias src="cd $SRC"
alias srcrui="cd $SRCRUI"
alias tmp="cd $TMP"
alias train="cd $TRAIN"
alias drive="cd $DRIVE"

alias fcfg="cd $FCFG"
alias scfg="cd $SCFG"
alias dcfg="cd $DCFG"
alias ucfg="cd $UCFG"

NFW=${NEPI_BASE}/nepi_engine/etc/fw_version.txt
alias nfws="cat ${NFW}"

function nfwu() {
  fw_version=$1
  sudo cat /dev/null > $NFW
  echo "${fw_version}" | sudo tee -a $NFW
}
export -f nfwu

HELPN="${HELPN}
################################
## NEPI folder shortcuts ##
################################
ai = ${NEPI_STORAGE}/ai_models
aifs = ${NEPI_BASE}/nepi_engine/share/nepi_aifs
api = ${NEPI_BASE}/nepi_engine/lib/python3/dist-packages/nepi_api
apps = ${NEPI_BASE}/nepi_engine/share/nepi_apps
auto = ${NEPI_STORAGE}/automation_scripts
data = ${NEPI_STORAGE}/data
dist = ${NEPI_BASE}/nepi_engine/lib/python3/dist-packages/
drivers = ${NEPI_BASE}/nepi_engine/lib/nepi_drivers
engine = ${NEPI_BASE}/nepi_engine
etc = ${NEPI_BASE}/nepi_engine/etc
intstall = ${NEPI_STORAGE}/intstall
lib = ${NEPI_BASE}/nepi_engine/lib
libsdk = ${NEPI_BASE}/nepi_engine/lib/nepi_sdk
managers = ${NEPI_BASE}/nepi_engine/lib/nepi_managers
nepi = ${NEPI_BASE}
nfi = ${NEPI_STORAGE}/nepi_full_img
nfia = ${NEPI_STORAGE}/nepi_full_img_archive
nimg = ${NEPI_STORAGE}/nepi_images
rui = ${NEPI_BASE}/nepi_rui/src/rui_webserver/rui-app/src
rui_env = ${NEPI_BASE}/nepi_rui
setupn = ${NEPI_STORAGE}/nepi_src/${NEPI_BUILD_REPO_NAME}/nepi_setup/scripts
scripts = ${NEPI_BASE}/scripts
sdk = ${NEPI_BASE}/nepi_engine/lib/python3/dist-packages/nepi_sdk
share = ${NEPI_BASE}/nepi_engine/share
src = ${NEPI_STORAGE}/nepi_src/${NEPI_BUILD_REPO_NAME}/src
srcrui = ${NEPI_STORAGE}/nepi_src/${NEPI_BUILD_REPO_NAME}/src/nepi_engine/nepi_rui/src/rui_webserver/rui-app/src
tmp = ${NEPI_STORAGE}/tmp
train = ${NEPI_STORAGE}/ai_training
drive = ${NEPI_STORAGE}

fcfg = ${NEPI_FACTORY_CONFIG}
scfg = ${NEPI_SYSTEM_CONFIG}
dcfg = ${NEPI_DOCKER_CONFIG}
ucfg = ${NEPI_STORAGE}/user_cfg

nfws = Show Installed NEPI Firmware Version
nfwu = Update NEPI Firmware Version with provided value"



# Print out the NEPI shortcuts
function nepihelp(){
    echo "$HELPN"
}



NROS=${NEPI_BASE}/nepi_engine/setup.bash
ROS=/opt/ros/noetic/setup.bash
HAS_ROS=$(dpkg -l | grep ros-)
if [ 1 ]; then # [[ -z "$HAS_ROS" ]]; then
      # Source ROS Env
      if [[ -f "$NROS" ]]; then
        #echo "Sourcing ros bash ${NROS}"
        source ${NROS}
      elif [[ -f "$ROS" ]]; then
        #echo "Sourcing ros bash ${ROS}" 
        source ${ROS}
      fi
      export NEEDS_ROS=0
fi

##### NEPI SETUP #####
export NEPI_REMOTE_SETUP=0
export NEPI_TARGET_SRC_DIR=${NEPI_STORAGE}/nepi_src
export PATH=${PATH}:${SCRIPTS}
