#!/bin/bash

##
## Copyright (c) 2024 Numurus <https://www.numurus.com>.
##
## This file is part of nepi setup tools (nepi_setup) repo
## (see https://github.com/nepi-engine/nepi_setup)
##
## License: nepi setup tools are licensed under the "Numurus Software License", 
## which can be found at: <https://numurus.com/wp-content/uploads/Numurus-Software-License-Terms.pdf>
##
## Redistributions in source code must retain this top-level comment block.
## Plagiarizing this software to sidestep the license obligations is illegal.
##
## Contact Information:
## ====================
## - mailto:nepi@numurus.com
##


# This file contains nepi pc dev aliases and sources nepi bash utils

if [[ ! -n $CONFIG_USER ]]; then
    CONFIG_USER=$(id -un)
    if [[ ${CONFIG_USER} == 'root' ]]; then
        CONFIG_USER=$SUDO_USER
    fi
fi
if [[ ! -n $CONFIG_USER ]]; then
    id -nu 1000
fi

NEPI_UTILS_FILE=/home/${CONFIG_USER}/.nepi_bash_utils
source $NEPI_UTILS_FILE


################################
export NEPI_REMOTE_SETUP=1
################################

HELPN="${UTILSN}"


###################################
# NEPI SSH Agent Config
###################################

 


ssh_key_path=/home/${CONFIG_USER}/.ssh/nepi_default_ssh_key
if [[ -z NEPI_SSH_KEY_PATH ]]; then
  NEPI_SSH_KEY_PATH=$ssh_key_path
fi

nepi_port=2222

# Setup Connection Shortcuts
# Setup Connection Shortcuts
alias sshn="ssh -o StrictHostKeyChecking=no -p $nepi_port -i $NEPI_SSH_KEY_PATH ${NEPI_USER}@nepi"
alias sshnv="ssh -vvv -o StrictHostKeyChecking=no -p $nepi_port -i $NEPI_SSH_KEY_PATH ${NEPI_USER}@nepi"
alias scpn="scp -o StrictHostKeyChecking=no -P $nepi_port -i $NEPI_SSH_KEY_PATH ${NEPI_USER}@nepi"
alias sftpn="sftp -o StrictHostKeyChecking=no -P $nepi_port -i $NEPI_SSH_KEY_PATH ${NEPI_USER}@nepi"

function sftpnl(){
sftp -o StrictHostKeyChecking=no -P $nepi_port -i $NEPI_SSH_KEY_PATH ${NEPI_USER}@nepi:../.."$@"
}




function sshnhc(){
  echo "Checking NEPI Device Clock"
  date_str=$(ssh -o StrictHostKeyChecking=no -p 22 -i $NEPI_SSH_KEY_PATH ${NEPI_HOST_USER}@nepihost "date -I")
  year_str="${date_str%%-*}"
  if [[ $year_str -lt 2026 ]]; then
    echo "Upating Clock"
    ssh -o StrictHostKeyChecking=no -p 22 -i $NEPI_SSH_KEY_PATH ${NEPI_HOST_USER}@nepihost "sudo -S date --set=@$(date +%s)"
  fi
  # date_str=$(ssh -o StrictHostKeyChecking=no -p 22 -i $NEPI_SSH_KEY_PATH ${NEPI_HOST_USER}@nepihost "date -I")
  # year_str="${date_str%%-*}"
  # if [[ $year_str -lt 2026 ]]; then
  #   echo "Failed to Update Clock"
  #   ssh -o StrictHostKeyChecking=no -p 22 -i $NEPI_SSH_KEY_PATH ${NEPI_HOST_USER}@nepihost "sudo -S date --set=@$(date +%s)"
  #   return 1
  # else
  #   echo "Remote Clock Updated to ${date_str}"
  #   return 0
  # fi  
}

# Setup Connection Shortcuts
function sshnh(){
  ssh -o StrictHostKeyChecking=no -p 22 -i $NEPI_SSH_KEY_PATH -t ${NEPI_HOST_USER}@nepihost "sudo -S date --set=@$(date +%s); exec bash -l"
}
function sshnhv(){
  ssh -vvv -o StrictHostKeyChecking=no -p 22 -i $NEPI_SSH_KEY_PATH -t ${NEPI_HOST_USER}@nepihost "sudo -S date --set=@$(date +%s); exec bash -l"
}

alias scpnh="scp -o StrictHostKeyChecking=no -P 22 -i $NEPI_SSH_KEY_PATH ${NEPI_HOST_USER}@nepihost"
alias sftpnh="sftp -o StrictHostKeyChecking=no -P 22 -i $NEPI_SSH_KEY_PATH ${NEPI_HOST_USER}@nepihost"


function sftpnhl(){
sftp -o StrictHostKeyChecking=no -P 22 -i $NEPI_SSH_KEY_PATH ${NEPI_HOST_USER}@nepihost:../.."$@"
}




HELPN="${HELPN}
################################
### NEPI SSH UTIL FUNCTIONS
################################
sshn = SSH into NEPI Software System
sshnv = SSH into NEPI Software System Verbose
sshnh = SSH into NEPI Host System
sshnhv = SSH into NEPI Host System Verbose
sshnhc = Sync NEPI Host System Clock
scpn = SCPN into NEPI
sftpn = SFTP into NEPI
sshnh = SSH into NEPI HOST
scpnh = SCPN into NEPI HOST
sftpnh = SFTP into NEPI HOST"




###################################
#NEPI folder shortcuts
###################################
export AI="${NEPI_STORAGE}/ai_models"
export AIF="${NEPI_BASE}/nepi_engine/share/nepi_ai_ifs"
export API="${NEPI_BASE}/nepi_engine/lib/python3/dist-packages/nepi_api"
export APPS="${NEPI_BASE}/nepi_engine/share/nepi_apps"
export AUTO="${NEPI_STORAGE}/automation_scripts"
export DATA="${NEPI_STORAGE}/data"
export DIST="${NEPI_BASE}/nepi_engine/lib/python3/dist-packages"
export DRIVERS="${NEPI_BASE}/nepi_engine/lib/nepi_drivers"
export ENGINE="${NEPI_BASE}/nepi_engine"
export ETC="${NEPI_BASE}/nepi_engine/etc"
export INSTALL="${NEPI_STORAGE}/intstall"
export LAUNCH="${NEPI_BASE}/nepi_engine/share/nepi_env/launch"
export LIB="${NEPI_BASE}/nepi_engine/lib"
export LIBSDK="${NEPI_BASE}/nepi_engine/lib/nepi_sdk"
export MANAGERS="${NEPI_BASE}/nepi_engine/lib/nepi_managers"
export NEPI="${NEPI_BASE}"
export NIMG="${NEPI_STORAGE}/nepi_images"
export NFI="${NEPI_STORAGE}/nepi_full_img"
export NFIA="${NEPI_STORAGE}/nepi_full_img_archive"
export RUI="${NEPI_BASE}/nepi_rui/src/rui_webserver/rui-app/src"
export RUI_ENV="${NEPI_BASE}/nepi_rui"
export SDK="${NEPI_BASE}/nepi_engine/lib/python3/dist-packages/nepi_sdk"
export SHARE="${NEPI_BASE}/nepi_engine/share"
export SRC="${NEPI_STORAGE}/nepi_src/${NEPI_BUILD_REPO_FOLDER}/src"
export SRCRUI="${NEPI_STORAGE}/nepi_src/${NEPI_BUILD_REPO_FOLDER}/src/nepi_rui/src/rui_webserver/rui-app/src"
export TMP="${NEPI_STORAGE}/tmp"
export DRIVE="${NEPI_STORAGE}"




#NEPI sftp folder shortcuts
# Function to open sftp to location on nepi device
# Example call: sftpnl '${NEPI_STORAGE}'

function ai(){
	sftpnl $AI
}	
function aifs(){
	sftpnl $AIFS
}	
function api(){
	sftpnl $API
}	
function apps(){
	sftpnl $APPS
}
function auto(){
	sftpnl $AUTO
}
function data(){
	sftpnl $DATA
}	
function dist(){
	sftpnl $DIST
}	
function drivers(){
	sftpnl $DRIVERS
}	
function engine(){
	sftpnl $ENGINE
}
function etc(){
	sftpnl $ETC
}	
function intstall(){
	sftpnl $INSTALL
}	
function lib(){
	sftpnl $LIB
}	
function libsdk(){
	sftpnl $LIBSDK
}	
function managers(){
	sftpnl $MANAGERS
}	
function nepi(){
	sftpnl $NEPI
}	
function nfi(){
	sftpnl $NFI
}	
function nfia(){
	sftpnl $NFIA
}	
function nimg(){
	sftpnl $NIMG
}	
function rui(){
	sftpnl $RUI
}
function rui_env(){
	sftpnl $RUI_ENV
}	
function sdk(){
	sftpnl $SDK
}	
function share(){
	sftpnl $SHARE
}	
function src(){
	sftpnl $SRC
}	
function srcrui(){
	sftpnl $SRCRUI
}
function tmp(){
	sftpnl $TMP
}	
function drive(){
	sftpnl $DRIVE
}

export DCFG="${NEPI_DOCKER_CONFIG}"
export FCFG="${NEPI_FACTORY_CONFIG}"
export SCFG="${NEPI_SYSTEM_CONFIG}"
export UCFG="${NEPI_STORAGE}/user_cfg"

function dcfg(){
	sftpnhl $DCFG
}

function fcfg(){
	sftpnhl $FCFG
}	

function scfg(){
	sftpnhl $SCFG
}	

function ucfg(){
	sftpnhl $UCFG
}	



HELPN="${HELPN}
################################
## NEPI sftp folder shortcuts ##
################################
drive = ${NEPI_STORAGE}
ai = ${NEPI_STORAGE}/ai_models
aifs = ${NEPI_BASE}/nepi_engine/share/nepi_aifs
api = ${NEPI_BASE}/nepi_engine/lib/python3/dist-packages/nepi_api
apps = ${NEPI_BASE}/nepi_engine/share/nepi_apps
auto = ${NEPI_STORAGE}/automation_scripts
data = ${NEPI_STORAGE}/data
dist = ${NEPI_BASE}/nepi_engine/lib/python3/dist-packages/
drivers = ${NEPI_BASE}/nepi_engine/lib/nepi_drivers
engine = ${NEPI_BASE}/nepi_engine
etc = ${NEPI_BASE}/nepi_engine/etc
intstall = ${NEPI_STORAGE}/intstall
lib = ${NEPI_BASE}/nepi_engine/lib
libsdk = ${NEPI_BASE}/nepi_engine/lib/sdk
managers = ${NEPI_BASE}/nepi_engine/lib/nepi_managers
nepi = ${NEPI_BASE}
nfi = ${NEPI_STORAGE}/nepi_full_img
nfia = ${NEPI_STORAGE}/nepi_full_img_archive
nimg = ${NEPI_STORAGE}/nepi_images
rui = ${NEPI_BASE}/rui/src/rui_webserver/rui-app/src
rui_env = ${NEPI_BASE}/rui
sdk = ${NEPI_BASE}/nepi_engine/lib/python3/dist-packages/nepi_sdk
share = ${NEPI_BASE}/nepi_engine/share
src = ${NEPI_STORAGE}/nepi_src/${NEPI_BUILD_REPO_FOLDER}/src
srcrui = ${NEPI_STORAGE}/nepi_src/${NEPI_BUILD_REPO_FOLDER}/src/nepi_rui/src/rui_webserver/rui-app/src
tmp = ${NEPI_STORAGE}/tmp
dcfg = ${NEPI_DOCKER_CONFIG}
fcfg = ${NEPI_FACTORY_CONFIG}
scfg = ${NEPI_SYSTEM_CONFIG}
ucfg = ${NEPI_STORAGE}/user_cfg"




export NTEST='NEPI'

# Print out the nepi shortcuts
function nepihelp(){
    echo "$HELPN"
}

export -f nepihelp

export NEPI_REMOTE_SETUP=1
export NEPI_TARGET_SRC_DIR=${NEPI_STORAGE}/nepi_src
