#!/bin/bash

##
## Copyright (c) 2024 Numurus <https://www.numurus.com>.
##
## This file is part of nepi setup tools (nepi_setup) repo
## (see https://github.com/nepi-engine/nepi_setup)
##
## License: nepi setup tools are licensed under the "Numurus Software License", 
## which can be found at: <https://numurus.com/wp-content/uploads/Numurus-Software-License-Terms.pdf>
##
## Redistributions in source code must retain this top-level comment block.
## Plagiarizing this software to sidestep the license obligations is illegal.
##
## Contact Information:
## ====================
## - mailto:nepi@numurus.com
##


# This file contains nepi pc dev aliases and sources nepi bash utils

if [[ ! -n $CONFIG_USER ]]; then
    CONFIG_USER=$(id -un)
    if [[ ${CONFIG_USER} == 'root' ]]; then
        CONFIG_USER=$SUDO_USER
    fi
fi
if [[ ! -n $CONFIG_USER ]]; then
    id -nu 1000
fi

NEPI_UTILS_FILE=/home/${CONFIG_USER}/.nepi_bash_utils
source $NEPI_UTILS_FILE


################################
export NEPI_REMOTE_SETUP=1
################################

HELPN="${UTILSN}"


###################################
# NEPI SSH Agent Config
###################################


# Clear Known Host Keys
function ckeys(){
  kh_file=/home/${CONFIG_USER}/.ssh/known_hosts
  if [[ -f "$kh_file" ]]; then
    rm $kh_file
  fi
}
export -f ckeys


function switchnd(){
  if [[ "$NEPI_IN_CONTAINER" -eq 1 ]]; then
    echo "Switching to Device Deployment"
    UPDATE='export NEPI_IN_CONTAINER=0'
  else
    echo "Switching to Container Deployment"
    UPDATE='export NEPI_IN_CONTAINER=1'
  fi

  ## Update NEPI_IN_CONTAINER
  FILE=/home/${CONFIG_USER}/.bashrc
  KEY='export NEPI_IN_CONTAINER'
  sudo sed -i "/^$KEY/c\\$UPDATE" "$FILE"

  # Do Export Updates
  export NEPI_IN_CONTAINER=$NEPI_IN_CONTAINER
  if [[ "$NEPI_IN_CONTAINER" -eq 1 ]]; then
    nepi_port=2222
    nepihost=nepihost
  else
    nepi_port=22
    nepihost=nepi
    
  fi

  # Clear known keys
  ckeys
  
  sbrc

}

if [[ "$NEPI_IN_CONTAINER" -eq 1 ]]; then
  nepi_port=2222
  nepihost=nepihost
else
  nepi_port=22
  nepihost=nepi
fi





# Setup Connection Shortcuts
# Setup Connection Shortcuts
alias sshn="ssh -o StrictHostKeyChecking=no -p $nepi_port -i $NEPI_SSH_KEY_PATH nepi@nepi"
alias scpn="scp -o StrictHostKeyChecking=no -P $nepi_port -i $NEPI_SSH_KEY_PATH nepi@nepi"
alias sftpn="sftp -o StrictHostKeyChecking=no -P $nepi_port -i $NEPI_SSH_KEY_PATH nepi@nepi"


function sshnhc(){
  echo "Checking NEPI Device Clock"
  date_str=$(ssh -o StrictHostKeyChecking=no -p 22 -i $NEPI_SSH_KEY_PATH ${nepihost}@${nepihost} "date -I")
  year_str="${date_str%%-*}"
  if [[ $year_str -lt 2026 ]]; then
    echo "Upating Clock"
    ssh -o StrictHostKeyChecking=no -p 22 -i $NEPI_SSH_KEY_PATH ${nepihost}@${nepihost} "sudo -S date --set=@$(date +%s)"
  fi
  date_str=$(ssh -o StrictHostKeyChecking=no -p 22 -i $NEPI_SSH_KEY_PATH ${nepihost}@${nepihost} "date -I")
  year_str="${date_str%%-*}"
  if [[ $year_str -lt 2026 ]]; then
    echo "Failed to Update Clock"
    ssh -o StrictHostKeyChecking=no -p 22 -i $NEPI_SSH_KEY_PATH ${nepihost}@${nepihost} "sudo -S date --set=@$(date +%s)"
    return 1
  else
    echo "Remote Clock Updated to ${date_str}"
    return 0
  fi  
}
# Setup Connection Shortcuts
function sshnh(){
  sshnhc
  ssh -o StrictHostKeyChecking=no -p 22 -i $NEPI_SSH_KEY_PATH ${nepihost}@${nepihost}
}


alias scpnh="scp -o StrictHostKeyChecking=no -P 22 -i $NEPI_SSH_KEY_PATH ${nepihost}@${nepihost}"
alias sftpnh="sftp -o StrictHostKeyChecking=no -P 22 -i $NEPI_SSH_KEY_PATH ${nepihost}@${nepihost}"

alias sshnr="ssh -o StrictHostKeyChecking=no -p 22 -i $NEPI_SSH_KEY_PATH ${nepihost}@nepirecovery"




function sftpnl(){
sftp -o StrictHostKeyChecking=no -P $nepi_port -i $NEPI_SSH_KEY_PATH nepi@nepi:../.."$@"
}

function sftpnhl(){
sftp -o StrictHostKeyChecking=no -P 22 -i $NEPI_SSH_KEY_PATH ${nepihost}@${nepihost}:../.."$@"
}


HELPN="${HELPN}
################################
### NEPI SSH UTIL FUNCTIONS
################################
sshn = SSH into NEPI Software System
sshnh = SSH into NEPI Host System
sshnhc = Sync NEPI Host System Clock
scpn = SCPN into NEPI
sftpn = SFTP into NEPI
sshnh = SSH into NEPI HOST
scpnh = SCPN into NEPI HOST
sftpnh = SFTP into NEPI HOST
ckeys = Clear known host keys"




SSH_ENV="$HOME/.ssh/environment"

function run_ssh_env {
  . "${SSH_ENV}" > /dev/null
}

function start_ssh_agent {
  echo "Initializing new SSH agent..."
  ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
  echo "succeeded"
  chmod 600 "${SSH_ENV}"

  run_ssh_env;

  ssh-add ~/.ssh/id_rsa;
}

if [ -f "${SSH_ENV}" ]; then
  run_ssh_env;
  ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
    start_ssh_agent;
  }
else
  : # Do Nothing
fi


###################################
#NEPI folder shortcuts
###################################
export AI="/mnt/nepi_storage/ai_models"
export AIF="/opt/nepi/nepi_engine/share/nepi_ai_ifs"
export API="/opt/nepi/nepi_engine/lib/python3/dist-packages/nepi_api"
export APPS="/opt/nepi/nepi_engine/share/nepi_apps"
export AUTO="/mnt/nepi_storage/automation_scripts"
export DATA="/mnt/nepi_storage/data"
export DIST="/opt/nepi/nepi_engine/lib/python3/dist-packages"
export DRIVERS="/opt/nepi/nepi_engine/lib/nepi_drivers"
export ENGINE="/opt/nepi/nepi_engine"
export ETC="/opt/nepi/nepi_engine/etc"
export INSTALL="/mnt/nepi_storage/intstall"
export LAUNCH="/opt/nepi/nepi_engine/share/nepi_env/launch"
export LIB="/opt/nepi/nepi_engine/lib"
export LIBSDK="/opt/nepi/nepi_engine/lib/nepi_sdk"
export MANAGERS="/opt/nepi/nepi_engine/lib/nepi_managers"
export NEPI="/opt/nepi"
export NIMG="/mnt/nepi_storage/nepi_images"
export NFI="/mnt/nepi_storage/nepi_full_img"
export NFIA="/mnt/nepi_storage/nepi_full_img_archive"
export RUI="/opt/nepi/nepi_rui/src/rui_webserver/rui-app/src"
export RUI_ENV="/opt/nepi/nepi_rui"
export SDK="/opt/nepi/nepi_engine/lib/python3/dist-packages/nepi_sdk"
export SHARE="/opt/nepi/nepi_engine/share"
export SRC="/mnt/nepi_storage/nepi_src/nepi_engine_ws/src"
export SRCRUI="/mnt/nepi_storage/nepi_src/nepi_engine_ws/src/nepi_rui/src/rui_webserver/rui-app/src"
export TMP="/mnt/nepi_storage/tmp"
export DRIVE="/mnt/nepi_storage"




#NEPI sftp folder shortcuts
# Function to open sftp to location on nepi device
# Example call: sftpnl '/mnt/nepi_storage'

function ai(){
	sftpnl $AI
}	
function aifs(){
	sftpnl $AIFS
}	
function api(){
	sftpnl $API
}	
function apps(){
	sftpnl $APPS
}
function auto(){
	sftpnl $AUTO
}
function data(){
	sftpnl $DATA
}	
function dist(){
	sftpnl $DIST
}	
function drivers(){
	sftpnl $DRIVERS
}	
function engine(){
	sftpnl $ENGINE
}
function etc(){
	sftpnl $ETC
}	
function intstall(){
	sftpnl $INSTALL
}	
function lib(){
	sftpnl $LIB
}	
function libsdk(){
	sftpnl $LIBSDK
}	
function managers(){
	sftpnl $MANAGERS
}	
function nepi(){
	sftpnl $NEPI
}	
function nfi(){
	sftpnl $NFI
}	
function nfia(){
	sftpnl $NFIA
}	
function nimg(){
	sftpnl $NIMG
}	
function rui(){
	sftpnl $RUI
}
function rui_env(){
	sftpnl $RUI_ENV
}	
function sdk(){
	sftpnl $SDK
}	
function share(){
	sftpnl $SHARE
}	
function src(){
	sftpnl $SRC
}	
function srcrui(){
	sftpnl $SRCRUI
}
function tmp(){
	sftpnl $TMP
}	
function drive(){
	sftpnl $DRIVE
}

export DCFG="/mnt/nepi_config/docker_cfg"
export FCFG="/mnt/nepi_config/factory_cfg"
export SCFG="/mnt/nepi_config/system_cfg"
export UCFG="/mnt/nepi_storage/user_cfg"

function dcfg(){
	sftpnhl $DCFG
}

function fcfg(){
	sftpnhl $FCFG
}	

function scfg(){
	sftpnhl $SCFG
}	

function ucfg(){
	sftpnhl $UCFG
}	



HELPN="${HELPN}
################################
## NEPI sftp folder shortcuts ##
################################
drive = /mnt/nepi_storage
ai = /mnt/nepi_storage/ai_models
aifs = /opt/nepi/nepi_engine/share/nepi_aifs
api = /opt/nepi/nepi_engine/lib/python3/dist-packages/nepi_api
apps = /opt/nepi/nepi_engine/share/nepi_apps
auto = /mnt/nepi_storage/automation_scripts
data = /mnt/nepi_storage/data
dist = /opt/nepi/nepi_engine/lib/python3/dist-packages/
drivers = /opt/nepi/nepi_engine/lib/nepi_drivers
engine = /opt/nepi/nepi_engine
etc = /opt/nepi/nepi_engine/etc
intstall = /mnt/nepi_storage/intstall
lib = /opt/nepi/nepi_engine/lib
libsdk = /opt/nepi/nepi_engine/lib/sdk
managers = /opt/nepi/nepi_engine/lib/nepi_managers
nepi = /opt/nepi
nfi = /mnt/nepi_storage/nepi_full_img
nfia = /mnt/nepi_storage/nepi_full_img_archive
nimg = /mnt/nepi_storage/nepi_images
rui = /opt/nepi/rui/src/rui_webserver/rui-app/src
rui_env = /opt/nepi/rui
sdk = /opt/nepi/nepi_engine/lib/python3/dist-packages/nepi_sdk
share = /opt/nepi/nepi_engine/share
src = /mnt/nepi_storage/nepi_src/nepi_engine_ws/src
srcrui = /mnt/nepi_storage/nepi_src/nepi_engine_ws/src/nepi_rui/src/rui_webserver/rui-app/src
tmp = /mnt/nepi_storage/tmp
dcfg = /mnt/nepi_config/docker_cfg
fcfg = /mnt/nepi_config/factory_cfg
scfg = /mnt/nepi_config/system_cfg
ucfg = /mnt/nepi_storage/user_cfg"


###################################
#NEPI PC Setup Shortcuts
###################################


## NEPI deploy complete
alias nepisetup="
source ${NEPI_SETUP_REPO_FOLDER}/scripts/dev_pc_setup.sh"


if [[ -d "/home/${CONFIG_USER}/nepi_engine_ws/nepi_setup/scripts" ]]; then
  setup_folder="/home/${CONFIG_USER}/nepi_engine_ws/nepi_setup/scripts"
else
  setup_folder="/home/${CONFIG_USER}/nepi_setup/scripts"
fi

export NSETUP=$setup_folder

alias nsetup="cd ${NSETUP}"

HELPN="${HELPN}
################################
## NEPI PC Setup Shortcuts ##
################################
nepisetup = Rerun the pc_dev_setup script
nsetup = Change Dir to the NEPI setup scripts folder"


export NTEST='NEPI'

# Print out the nepi shortcuts
function nepihelp(){
    echo "$HELPN"
}

export -f nepihelp

export NEPI_REMOTE_SETUP=1
export NEPI_TARGET_SRC_DIR=${NEPI_STORAGE}/nepi_src
