#!/bin/bash

##
## Copyright (c) 2024 Numurus <https://www.numurus.com>.
##
## This file is part of nepi setup tools (nepi_setup) repo
## (see https://github.com/nepi-engine/nepi_setup)
##
## License: nepi setup tools are licensed under the "Numurus Software License", 
## which can be found at: <https://numurus.com/wp-content/uploads/Numurus-Software-License-Terms.pdf>
##
## Redistributions in source code must retain this top-level comment block.
## Plagiarizing this software to sidestep the license obligations is illegal.
##
## Contact Information:
## ====================
## - mailto:nepi@numurus.com
##

# This file contains nepi docker host system aliases and sources nepi bash utils

#echo "########################"
#echo "NEPI Docker Aliases"
#echo "########################"

##########################################
if [[ ! -n $CONFIG_USER ]]; then
    CONFIG_USER=$(id -un)
    if [[ ${CONFIG_USER} == 'root' ]]; then
        CONFIG_USER=$SUDO_USER
    fi
fi
if [[ ! -n $CONFIG_USER ]]; then
    id -nu 1000
fi


NEPI_UTILS_FILE=/home/${CONFIG_USER}/.nepi_bash_utils
source $NEPI_UTILS_FILE


################################
export NEPI_REMOTE_SETUP=0
################################

HELPN="${UTILSN}"


#############################
# NEPI SHORTCUT FUNCTIONS
#############################

function nepipull(){
  sudo -v
  docker_link=$1
  if pingi; then
    start_ids=$(echo $(sudo docker images -q))
    bash ${NEPI_DOCKER_CONFIG}/nepi_docker_pull.sh $docker_link
    end_ids=$(echo $(sudo docker images -q))
    if [[ ${start_ids} != ${end_ids} ]]; then
      bash ${NEPI_DOCKER_CONFIG}/nepi_docker_start.sh
    fi
  fi
}
export -f nepipull


function nepipush(){
  sudo -v
  script_user=$(id -un)
  if [[ ${script_user} != 'root' ]]; then
      echo "This script must be run as root. Type 'sudo su' before running this process."
      return 1
  fi

  hub_tag=$1
  echo "Pushing NEPI Docker Image"
  bash ${NEPI_DOCKER_CONFIG}/nepi_docker_push.sh $hub_tag
  bash ${NEPI_DOCKER_CONFIG}/nepi_docker_start.sh
}
export -f nepipull


# NEPI stop and start shortcuts
function nepistop(){
  sudo -v
  echo "Stopping NEPI Docker Service"
  sudo systemctl stop nepi_docker
  bash ${NEPI_DOCKER_CONFIG}/nepi_docker_stop.sh
}
export -f nepistop

function nepistart(){
  sudo -v
  echo "Stopping NEPI Docker Service"
  sudo systemctl stop nepi_docker
  bash ${NEPI_DOCKER_CONFIG}/nepi_docker_start.sh
}
export -f nepistart

function nepidev(){
  sudo -v
  echo "Stopping NEPI Docker Service"
  sudo systemctl stop nepi_docker
  run_cmd=$1
  bash ${NEPI_DOCKER_CONFIG}/nepi_docker_dev.sh $run_cmd
}
export -f nepidev



function nepilogin(){
  sudo -v
  nuser=$1
  bash ${NEPI_DOCKER_CONFIG}/nepi_docker_login.sh  $nuser    
}
export -f nepilogin

function nepiloginroot(){
  sudo -v
  nuser=root
  bash ${NEPI_DOCKER_CONFIG}/nepi_docker_login.sh $nuser 
}
export -f nepiloginroot



function nepicommit(){
  sudo -v
  commit_desc=$1
  restart=$2
  if bash ${NEPI_DOCKER_CONFIG}/nepi_docker_commit.sh $commit_desc; then
    if [[ -z $restart ]]; then
      nepistart
    elif [[ "$restart" -eq 1 ]]; then
      nepistart
    fi
  fi
}
export -f nepicommit



function nepiswitch(){
  sudo -v
  bash ${NEPI_DOCKER_CONFIG}/nepi_docker_switch.sh
}
export -f nepiswitch


function nepiinit(){
  sudo -v
  import_path=${NEPI_STORAGE}/nepi_images
  if [[ -n "$1" ]]; then
    if [[ -f "$1" ]]; then
      image_path=$1
    elif [[ -n "$2" ]]; then
      image_path=${import_path}/${$2}
    fi
  fi

  if [[ -d "$import_path" ]]; then
        image_count=$(sudo docker images --format "{{.Repository}}:{{.Tag}}" | wc -l)
        if [ "$image_count" -gt 0 ]; then
          echo "WARNING: IF YOU PROCEED, ALL EXISTING NEPI IMAGES WILL BE STOPPED AND REMOVED"
          echo ""
          response=$(ask_yes_no "Do you want to proceed?")
        else
            response=yes
        fi

        if [ "$response" == "yes" ]; then
          
          selected=$(select_file_from_folder $import_path | tail -n1)
          if [[ -n "$selected" ]]; then
            echo "Initializing with NEPI Image file ${selected}"
            image_path="${import_path}/${selected}"
          else
              echo "No NEPI Image Files Found in: ${import_path}"
              return 1
          fi  
        else
            echo "Action cancelled."
            return 1
        fi  
  fi

  if [[ -f "$image_path" ]]; then
    bash ${NEPI_DOCKER_CONFIG}/nepi_docker_init.sh $image_path
  else
      echo "No NEPI Image Files Found in: ${import_path}"
      return 1
  fi  
  
}
export -f nepiinit



function nepidownload(){
  sudo -v
  nepi_image_link=$1
  bash ${NEPI_DOCKER_CONFIG}/nepi_docker_download.sh ${nepi_image_link}
}
export -f nepidownload


function nepiimport(){
  sudo -v
  import_path=${NEPI_STORAGE}/nepi_images
  if [[ -n "$1" ]]; then
    if [[ -f "$1" ]]; then
      image_path=$1
    elif [[ -n "$2" ]]; then
      image_path=${import_path}/${$2}
    fi
  fi

  if [[ -d "$import_path" ]]; then
      selected=$(select_file_from_folder $import_path | tail -n1)
      echo "Selected NEPI Image file ${selected}"
      if [[ -n "$selected" ]]; then
        echo "Importing NEPI Image file ${selected}"
        image_path="${import_path}/${selected}"
      else
          echo "No NEPI Image Files Found in: ${import_path}"
          return 1
      fi  
  fi
  echo "Calling NEPI Import script with file ${image_path}"
  if [[ -f "$image_path" ]]; then
    bash ${NEPI_DOCKER_CONFIG}/nepi_docker_import.sh $image_path
  else
      echo "No NEPI Image Files Found in: ${import_path}"
      return 1
  fi  
}
export -f nepiimport



function nepiretag(){
  sudo -v
  sw_desc=$1
  echo "Retagging NEPI Active Image with ${sw_desc}"
  bash ${NEPI_DOCKER_CONFIG}/nepi_docker_retag.sh $sw_desc
}
export -f nepiretag


function nepiexport(){
  sudo -v
  bash ${NEPI_DOCKER_CONFIG}/nepi_docker_export.sh $1
}
export -f nepiexport

function nepiexportclean(){
  sudo -v
  bash ${NEPI_DOCKER_CONFIG}/nepi_docker_export.sh 'clean'
}
export -f nepiexportclean


function nepisave(){
  sudo -v
  bash ${NEPI_DOCKER_CONFIG}/nepi_docker_save.sh $1
}
export -f nepisave


function nepiload(){
  sudo -v
  import_path=${NEPI_STORAGE}/nepi_images
  if [[ -n "$1" ]]; then
    if [[ -f "$1" ]]; then
      image_path=$1
    elif [[ -n "$2" ]]; then
      image_path=${import_path}/${$2}
    fi
  fi

  if [[ -d "$import_path" ]]; then
      selected=$(select_file_from_folder $import_path | tail -n1)
      echo "Selected NEPI Image file ${selected}"
      if [[ -n "$selected" ]]; then
        echo "Importing NEPI Image file ${selected}"
        image_path="${import_path}/${selected}"
      else
          echo "No NEPI Image Files Found in: ${import_path}"
          return 1
      fi  
  fi
  echo "Calling NEPI Load script with file ${image_path}"
  if [[ -f "$image_path" ]]; then
    bash ${NEPI_DOCKER_CONFIG}/nepi_docker_load.sh $image_path
  else
      echo "No NEPI Image Files Found in: ${import_path}"
      return 1
  fi  
}
export -f nepiload



function nepistatus(){
  sudo -v
  sudo systemctl status nepi_docker
}
export -f nepistatus

function nepilogs(){
  sudo -v
  sudo journalctl -u nepi_docker -f
}
export -f nepilogs


# NEPI stop and start shortcuts
function nepienable(){
  sudo -v
  sudo systemctl enable nepi_docker
  sudo systemctl start nepi_docker
  echo $(nepistatus)
}
export -f nepienable

function nepidisable(){
  sudo -v
  nepistop
  wait
  sudo systemctl disable nepi_docker
  echo "NEPI Docker Service disabled on next boot"
}
export -f nepidisable



function nepirestart(){
  sudo -v
  sudo systemctl restart nepi_docker
}
export -f nepirestart

function nepiupdate() {
  sudo -v

  bash ${NEPI_DOCKER_CONFIG}/nepi_docker_update.sh
}
export -f nepiupdate

function nepiprint(){
  sudo -v
  echo "NEPI DOCKER SETTINGS"
  echo "--------------------"
  print_yaml_file ${NEPI_DOCKER_CONFIG}/nepi_docker_config.yaml
  echo ""
  echo "NEPI SYSTEM SETTINGS"
  echo "--------------------"
  print_yaml_file ${NEPI_DOCKER_CONFIG}/nepi_docker_config.yaml
}
export -f nepiprint


function nepicreate(){
  sudo -v
  bash ${NEPI_DOCKER_CONFIG}/nepi_docker_create.sh
}
export -f nepicreate


## NEPI build shortcuts
alias nepibld="
sudo -v
SHOW_CONFIG_MENU=1
source $(NSETUP)/scripts/docker_config_setup.sh $SHOW_CONFIG_MENU
sbrc
nnet
pingn"



HELPN="${HELPN}
################################
## NEPI Docker Shortcut Functions ##
################################
nepistart = Start the NEPI docker container.
nepidev = Start the NEPI docker container in a dev mode with no processes running, and an OPTIONAL_RUN_COMMAND.
nepistop = Stop the running NEPI docker container.
nepilogin = Log into the running NEPI container as user 'nepi'.
nepiloginroot = Log into the running NEPI container as user 'root'.
nepiswitch = Switch to Inactive NEPI container on next boot or reststat.
nepicommit = Commit the running NEPI container wit provided COMMIT_DESCRIPTION, restarts nepi using new commit unless RESTART=0 is passed .
nepipull = Download and install a NEPI Docker image from the provided link
nepiinit = Reset, clear, and import new NEPI Image.
nepidownload = Download and install image from provided 'dropbox_shared_folder_link_address' in qoutes.
nepiimport = Import a NEPI image .tar file. Optional: Enter a file name or full file path.
nepiexport = Export the running NEPI container to a .tar file. Enter a file name or full file path.
nepiexportclean = Export the running NEPI container without a tailing description.
nepiload = Import a NEPI image .archive.tar file. Optional: Enter a file name or full file path.
nepisave = Save the active NEPI Image with all commits to a .archieve.tar file. Enter a file name or full file path.
nepitag = Update the Software Description field in the active NEPI container.
nepienable = Enable NEPI Docker service on next boot.
nepidisable = Disable NEPI Docker service on next boot.
nepirestart = Restart NEPI docker service.
nepistatus = Show the systemctl status for nepi_docker service.
nepilogs = Show live NEPI Docker service journal file.
nepibld = Build or Update the NEPI Docker File System from source code in ${NEPI_BUILD_REPO_FOLDER}.
nepiupdate = Run NEPI Docker bash, folders, files, and config update processes.
nepicreate = Export and Import a new NEPI Docker Image from running container
nepiprint = Print current NEPI DOCKER and SYSTEM configuration settings."

#nepilicense = Print the NEPI Software Licencse"



###################################
# NEPI SSH Agent Config
###################################








nepi_port=2222


ssh_key_path=/home/${CONFIG_USER}/.ssh/nepi_default_ssh_key
if [[ -z NEPI_SSH_KEY_PATH ]]; then
  NEPI_SSH_KEY_PATH=$ssh_key_path
fi

# Setup Connection Shortcuts
# Setup Connection Shortcuts
alias sshn="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p $nepi_port -i $NEPI_SSH_KEY_PATH ${NEPI_USER}@nepi"
alias sshnv="ssh -vvv -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p $nepi_port -i $NEPI_SSH_KEY_PATH ${NEPI_USER}@nepi"
alias scpn="scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P $nepi_port -i $NEPI_SSH_KEY_PATH ${NEPI_USER}@nepi"
alias sftpn="sftp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P $nepi_port -i $NEPI_SSH_KEY_PATH ${NEPI_USER}@nepi"


function sftpnl(){
sftp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P $nepi_port -i $NEPI_SSH_KEY_PATH ${NEPI_USER}@nepi:../.."$@"
}


HELPN="${HELPN}
################################
### NEPI SSH UTIL FUNCTIONS
################################
sshn = SSH into NEPI Software System
scpn = SCPN into NEPI
sftpn = SFTP into NEPI"







###################################
#NEPI folder shortcuts
###################################
export AI="${NEPI_STORAGE}/ai_models"
export AIF="${NEPI_BASE}/nepi_engine/share/nepi_ai_ifs"
export API="${NEPI_BASE}/nepi_engine/lib/python3/dist-packages/nepi_api"
export APPS="${NEPI_BASE}/nepi_engine/share/nepi_apps"
export AUTO="${NEPI_STORAGE}/automation_scripts"
export DATA="${NEPI_STORAGE}/data"
export DIST="${NEPI_BASE}/nepi_engine/lib/python3/dist-packages"
export DRIVE="${NEPI_STORAGE}"
export DRIVERS="${NEPI_BASE}/nepi_engine/lib/nepi_drivers"
export ENGINE="${NEPI_BASE}/nepi_engine"
export ETC="${NEPI_BASE}/nepi_engine/etc"
export INSTALL="${NEPI_STORAGE}/intstall"
export LAUNCH="${NEPI_BASE}/nepi_engine/share/nepi_env/launch"
export LIB="${NEPI_BASE}/nepi_engine/lib"
export LIBSDK="${NEPI_BASE}/nepi_engine/lib/nepi_sdk"
export MANAGERS="${NEPI_BASE}/nepi_engine/lib/nepi_managers"
export NEPI="${NEPI_BASE}"
export NIMG="${NEPI_STORAGE}/nepi_images"
export NFI="${NEPI_STORAGE}/nepi_full_img"
export NFIA="${NEPI_STORAGE}/nepi_full_img_archive"
export RUI="${NEPI_BASE}/nepi_rui/src/rui_webserver/rui-app/src"
export RUI_ENV="${NEPI_BASE}/nepi_rui"
export SDK="${NEPI_BASE}/nepi_engine/lib/python3/dist-packages/nepi_sdk"
export SHARE="${NEPI_BASE}/nepi_engine/share"
export SRC="${NEPI_BUILD_REPO_FOLDER}/src"
export SRCRUI="${NEPI_BUILD_REPO_FOLDER}/src/nepi_rui/src/rui_webserver/rui-app/src"
export TMP="${NEPI_STORAGE}/tmp"
export DRIVE="${NEPI_STORAGE}"




#NEPI sftp folder shortcuts
# Function to open sftp to location on nepi device
# Example call: sftpnl '${NEPI_STORAGE}'


function aifs(){
	sftpnl $AIFS
}	
function api(){
	sftpnl $API
}	
function apps(){
	sftpnl $APPS
}

function dist(){
	sftpnl $DIST
}	

function drivers(){
	sftpnl $DRIVERS
}	
function engine(){
	sftpnl $ENGINE
}
function etc(){
	sftpnl $ETC
}	

function lib(){
	sftpnl $LIB
}	
function libsdk(){
	sftpnl $LIBSDK
}	
function managers(){
	sftpnl $MANAGERS
}	

function rui(){
	sftpnl $RUI
}
function rui_env(){
	sftpnl $RUI_ENV
}	
function sdk(){
	sftpnl $SDK
}	
function share(){
	sftpnl $SHARE
}	




HELPN="${HELPN}
################################
## NEPI sftp folder shortcuts ##
################################

aifs=${NEPI_BASE}/nepi_engine/share/nepi_aifs
api=${NEPI_BASE}/nepi_engine/lib/python3/dist-packages/nepi_api
apps=${NEPI_BASE}/nepi_engine/share/nepi_apps
dist=${NEPI_BASE}/nepi_engine/lib/python3/dist-packages/

drivers=${NEPI_BASE}/nepi_engine/lib/nepi_drivers
engine=${NEPI_BASE}/nepi_engine
etc=${NEPI_BASE}/nepi_engine/etc
lib=${NEPI_BASE}/nepi_engine/lib
libsdk=${NEPI_BASE}/nepi_engine/lib/sdk
managers=${NEPI_BASE}/nepi_engine/lib/nepi_managers
nepi=${NEPI_BASE}
rui=${NEPI_BASE}/rui/src/rui_webserver/rui-app/src
rui_env=${NEPI_BASE}/rui
sdk=${NEPI_BASE}/nepi_engine/lib/python3/dist-packages/nepi_sdk
share=${NEPI_BASE}/nepi_engine/share"



###################################
#NEPIHOST folder shortcuts
#echo "Setting up NEPI Folder Shortcuts"
export NIMG="${NEPI_STORAGE}/nepi_images"

export NDRIVE="${NEPI_STORAGE}"

export DCFG="${NEPI_DOCKER_CONFIG}"
export FCFG="${NEPI_FACTORY_CONFIG}"
export SCFG="${NEPI_SYSTEM_CONFIG}"
export UCFG="${NEPI_STORAGE}/user_cfg"


# NEPI navigation shortcuts

alias nimg="cd $NIMG"
alias nssh="cd $NEPI_SSH_FOLDER"

alias ai="cd $AI"
alias auto="cd $AUTO"
alias data="cd $DATA"
alias drive="cd $DRIVE"
alias intstall="cd $INSTALL"
alias nepi="cd $NEPI"
alias nfi="cd $NFI"
alias nfia="cd $NFIA"
alias src="cd $SRC"
alias srcrui="cd $SRCRUI"
alias tmp="cd $TMP"
	
alias dcfg="cd $DCFG"
alias fcfg="cd $FCFG"
alias scfg="cd $SCFG"
alias ucfg="cd $UCFG"


export NDSETUP="${NEPI_DOCKER_CONFIG}"
alias ndsetup="cd ${NDSETUP}"

alias nfw="cat ${NEPI_BASE}/nepi_engine/etc/fw_version.txt"

HELPN="${HELPN}
################################
## NEPIHOST folder shortcuts ##
################################

nimg = ${NEPI_STORAGE}/nepi_images
nssh = ${NEPI_SSH_FOLDER}

ai = ${NEPI_STORAGE}/ai_models
auto = ${NEPI_STORAGE}/automation_scripts
data = ${NEPI_STORAGE}/data
drive = ${NEPI_STORAGE}
intstall = ${NEPI_STORAGE}/intstall
nfi = ${NEPI_STORAGE}/nepi_full_img
nfia = ${NEPI_STORAGE}/nepi_full_img_archive
nimg = ${NEPI_STORAGE}/nepi_images
src = ${NEPI_BUILD_REPO_FOLDER}/src
srcrui = ${NEPI_BUILD_REPO_FOLDER}/src/nepi_rui/src/rui_webserver/rui-app/src
tmp = ${NEPI_STORAGE}/tmp

dcfg = ${NEPI_DOCKER_CONFIG}
fcfg = ${NEPI_FACTORY_CONFIG}
scfg = ${NEPI_FACTORY_CONFIG}
ucfg = ${NEPI_STORAGE}/user_cfg

ndsetup = /mnt/nepi_config/docker_config

nfw = Show Installed NEPI FW Version"

# Print out the nepi shortcuts
function nepihelp(){
    echo "$HELPN"
}





