NEPI_USER: nepi
NEPI_ADMIN_USER: nepiadmin
NEPI_HOST_USER: nepihost
NEPI_USER_PW: nepi
NEPI_ADMIN_PW: nepiadmin
NEPI_HOST_PW: nepi
# NOTE: if set to 0, all none-nepi user accounts will be removed
NEPI_ALLOWS_USERS: 1
NEPI_DEVICE_ID: device1
NEPI_DEVICE_MD: unknown
NEPI_DEVICE_SN: '999999'
NEPI_VERSION: XpXpX
NEPI_SW_DESC: unknown
NEPI_SSH_PORT: 2222
NEPI_SSH_KEY: nepi_default_ssh_key
NEPI_WIRED_INTERFACE: unknown
NEPI_WIRED_NAME: NEPI_WIRED
NEPI_STATIC_IP: 192.168.179.103/24
NEPI_GATEWAY_IP: unknown
# NOTE: NEPI IP aliases are useful if you need to connect to other devices on the Network
NEPI_ALIAS_IP_1: 192.168.0.103/24
NEPI_ALIAS_IP_2: 192.168.1.103/24
NEPI_ALIAS_IP_3: NONE
# NOTE: If the subnet of your desired NTP source IP address is different then NEPI_STATIC_IP's subnet,
NEPI_NTP_IP: 192.168.179.5
# NOTE: If the subnet of your desired NTP source IP address is different then NEPI_STATIC_IP's subnet,
NEPI_VEHICLE_SUBNET: NONE
NEPI_NAV_IP: NONE
NEPI_NAV_IP_HNAV: NONE
NEPI_NAV_PORT_HNAV: NONE
NEPI_NAV_IP_NMEA: NONE
NEPI_NAV_PORT_NMEA: NONE
# NOTE: If enabled, the NEPI device will have internet connectiviy if connected to
NEPI_WIRED_INTERNET_ENABLED: 0
NEPI_WIRED_DHCP_ENABLED: 0
# NOTE: If set to "unknown", the first detected WiFi harware will be used
NEPI_WIFI_INTERFACE: unknown
NEPI_WIFI_ENABLED: 1
NEPI_WIFI_LOW_POWER_ENABLED: 1
NEPI_WIFI_CLIENT_ENABLED: 1
NEPI_WIFI_CLIENT_ID: NONE
NEPI_WIFI_CLIENT_PW: NONE
# NOTE: If set to "unknown", the first detected WiFi harware will be used
NEPI_HOTSPOT_INTERFACE: unknown
NEPI_HOTSPOT_ENABLED: 1
NEPI_HOTSPOT_NAME: NEPI_HOSTSPOT
NEPI_HOTSPOT_ID: NEPI
NEPI_HOTSPOT_ADD_DEVICE: 1
NEPI_HOTSPOT_ADD_SN: 1
NEPI_HOTSPOT_PW: nepi#12345
NEPI_WIFI_ACCESS_POINT_ENABLED: 0
NEPI_WIFI_ACCESS_POINT_ID: nepi_device_ap
NEPI_WIFI_ACCESS_POINT_PW: nepi_device_ap
NEPI_INSTALL: unknown
NEPI_PYTHON: 0
NEPI_HAS_CUDA: 0
NEPI_CUDA_VERSION: 0
NEPI_HAS_XPU: 0
NEPI_HAS_HAILO: 0
NEPI_HAILO_HW_VERSION: 0
NEPI_HAILO_SW_VERSION: 0
NEPI_FS_AB: 0
NEPI_VPN_ENABLED: 0
NEPI_VPN_VERSION: 0
NEPI_ROS: unknown
NEPI_ROS_IP: 192.168.179.103
NEPI_ROS_PORT: 11311
ROS_NAME: nepi
ROS_LOG_DIR: /mnt/nepi_storage/logs/ros_log
ROS_MASTER_URI: http://localhost:11311
ROS1_LAUNCH_FILE: nepi_base.launch
ROS2_PACKAGE: TBD
ROS2_LAUNCH_FILE: TBD
ROS2_LAUNCH_ARGS: TBD
# NEPI Hardware Host Options: jetson, arm64, amd64.
NEPI_HW_TYPE: unknown
# NEPI Hardware Host Model Options: ORIN, XAVIER, TX2, NANO, RPI4, GENERIC.
NEPI_HW_MODEL: unknown
NEPI_IN_CONTAINER: 1
NEPI_GB_CONTAINER: 30
# Note: If NEPI_RECOVERY_ENABLED enabled and NEPI_STATIC_IP is not 192.168.179.103,
NEPI_RECOVERY_ENABLED: 1
# NOTE: This is the time NEPI Docker service will
# NOTE:  This time may vary on different hardware configurations,
NEPI_BOOT_TIME: 60
NEPI_MANAGES_SERVICES: unknown
NEPI_MANAGES_USERS: 1
NEPI_MANAGES_HOSTNAME: 1
NEPI_MANAGES_NETWORK: 1
NEPI_MANAGES_TIME: 1
NEPI_MANAGES_SSH: 1
NEPI_MANAGES_SHARE: 1
NEPI_MANAGES_SOFTWARE: 1
# Note: If enabled, NEPI will setup docker configuration,
NEPI_MANAGES_DOCKER: 1
NEPI_BOOT_DEVICE: CONTAINER
NEPI_FS_DEVICE: CONTAINER
NEPI_STORAGE_DEVICE: CONTAINER
NEPI_DOCKER: /var/lib/docker/
#NEPI_DOCKER: /mnt/nepi_docker
NEPI_CONFIG: /mnt/nepi_config
NEPI_STORAGE: /mnt/nepi_storage
NEPI_SOURCE: /home/nepidev
NEPI_ENV: nepi_env
NEPI_HOME: /home/nepi
NEPI_BASE: /opt/nepi
NEPI_RUI: /opt/nepi/nepi_rui
NEPI_ENGINE: /opt/nepi/nepi_engine
NEPI_ETC: /opt/nepi/etc
NEPI_SCRIPTS: /opt/nepi/scripts
NEPI_DOCKER_CONFIG: /mnt/nepi_config/docker_cfg
NEPI_FACTORY_CONFIG: /mnt/nepi_config/factory_cfg
NEPI_SYSTEM_CONFIG: /mnt/nepi_config/system_cfg
NEPI_USR_CONFIG: /mnt/nepi_storage/user_cfg
# NOTE: It is recommended that these folders be create as their own partitions
NEPI_IMPORT_PATH: /mnt/nepi_storage/nepi_images
NEPI_EXPORT_PATH: /mnt/nepi_storage/nepi_images
