# sudo modprobe uvcvideo
# sudo rmmod uvcvideo
# options uvcvideo nodrop=1 timeout=5000 quirks=0x80
# sudo modprobe uvcvideo nodrop=0 timeout=8000 quirks=0x100
options uvcvideo  nodrop=1 timeout=8000 quirks=0x100
