[supervisord]
nodaemon=true


[program:nepi_ssh]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/nepi_ssh.log
stderr_logfile=/var/log/supervisor/nepi_ssh.err

[program:nepi_rui]
command=/bin/bash /opt/nepi/nepi_rui/etc/start_rui.sh
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/nepi_rui.log
stderr_logfile=/var/log/supervisor/nepi_rui.err

[program:nepi_engine]
command=/bin/bash -c "sudo -u nepi /opt/nepi/nepi_engine/etc/nepi_env/nepi_launch.sh"
autostart=true
autorestart=false
stdout_logfile=/var/log/supervisor/nepi_engine.log
stderr_logfile=/var/log/supervisor/nepi_engine.err


[program:nepi_license]
command=/usr/bin/python3 /opt/nepi/etc/license/nepi_check_license.py
directory=/opt/nepi/etc/license
autostart=true
startsecs=5
autorestart=true
stdout_logfile=/var/log/supervisor/nepi_license.log
stderr_logfile=/var/log/supervisor/nepi_license.err

#[program:nepi_samba]
#command=/usr/sbin/smbd -D
#autostart=true
#autorestart=false
#user=root
#stdout_logfile=/var/log/supervisor/nepi_samba.log
#stderr_logfile=/var/log/supervisor/nepi_samba.err





